4C-multiphysics/4C

.github/workflows/buildtest.yml, .github/workflows/checkcode.yml, .github/workflows/docker.yml, .gitlab/CODEOWNERS, CMakeLists.txt, README.md, cmake/functions/four_c_auto_define_module.cmake, docker/Dockerfile, src/core/comm/tests/4C_comm_utils_test.cpp, src/core/comm/tests/CMakeLists.txt
The following workflows are added:
- Build the docker image containing the dependencies (remove the newer
gcc compiler because the docker build takes too long otherwise. There
is limit of 6 hours.
- Checkcode which runs pre-commit (The codeowner check is left out as it
is tied to Gitlab)
- A first build and test workflow. We only run the minimal test as we
ran out of disk space when running all tests.
Once this is merged. We are able to test if the actions and triggers work as expected.
=> Add first Actions

.github/workflows/buildtest.yml, .github/workflows/checkcode.yml, .github/workflows/docker.yml, .github/workflows/documentation.yml
To not waste resources, we need to cancel redundant workflows
=> Add concurrency to auto-cancel workflows

.github/workflows/deploy.yml, .github/workflows/documentation.yml
Try to make the overview of actions a bit more intuitive by not showing the skipped deployment in PRs.
=> CI: use separate workflow for deployment

.github/workflows/buildtest.yml
Add a job after buildtest that fails if one prior job failed.
This is the simplest way (I'm aware of) to tell Github that all jobs must succeed.
=> Add buildtest summary

.github/actions/compute-and-check-dependencies-hash/action.yml, .github/workflows/docker.yml
This is the first part of the experiments in PR #17 . Once the `docker.yml` is on the default branch we can try to manually trigger the docker build and I will create another PR were we can try the docker update mechanism.
=> Allow manual build of the docker image

.github/workflows/buildtest.yml, .github/workflows/checkcode.yml, .github/workflows/docker.yml, .github/workflows/documentation.yml, dependencies/current/backtrace/install.sh, dependencies/current/qhull/install.sh, dependencies/current/suitesparse/install.sh, dependencies/current/superlu_dist/install.sh, dependencies/current/trilinos/install.sh, dependencies/testing/mathjax/install.sh, dependencies/testing/paraview/install.sh, docker/Dockerfile
This PR updates the docker image. I removed some unnecessary files from the docker image such that we save 3 GB for the resulting image. It is still quite large with 8.7 GB. But for now this should get us around disk space problems on the runner when building the image.
This is a follow-up to #19 .  I pushed the branch directly into the 4c repo in order to be able to use a manual workflow to update the docker image. After that the pipeline triggered by this PR should work :crossed_fingers: 
The update process is quite annoying at the moment because we cannot use a variable for `container.image` such that you need to manually replace all occurrences when you update the docker hash. At the moment, this is quite brittle as the I only check that the pulled files inside the repo match the …
=> Update the docker image

.github/workflows/buildtest.yml, .github/workflows/checkcode.yml
Let's skip a few checks that are not necessary on main.
=> CI: don't run checkcode and tests on main

.github/actions/build_4C/action.yml, .github/actions/download_4C_build/action.yml, .github/actions/upload_4C_build/action.yml, .github/workflows/buildtest.yml, .github/workflows/checkcode.yml, .github/workflows/documentation.yml
This PR preparing us to reuse more of the defined steps to build and test 4C in a workflow running every night.
* Extends `build_4C` that now internally calls `configure_4C` and prepares `ccache` if wanted.
* Adds actions to upload and download the build-folder from previous artifacts.
* separates clang build and test in PR testing.
=> Add further actions to reduce duplication

.github/actions/compute-and-check-dependencies-hash/action.yml
I messed up the condition. The check is now executed in places where it should not execute and vice versa.
=> Fix wrong skip check condition

README.md
Part of #42 
For now, I added the badges that Github already generates. I linked to the respective workflow overview. For docs, I link to the readthedocs page.
=> Add badges generated from workflows to README.md

README.md
Some links in our README to the readthedocs documentation were still based on the GitLab.pages. I updated them to the corresponding GitHub counterparts.
=> Update paths in the README

cmake/setup_global_options.cmake
With #85, we can now also enforce the last remaining ignored warning of clang-18
=> Enforce warning-free clang build

doc/readthedocs/developer_dirstructure.rst
Closes #58 
After unifying the file endings in #86 #98, this PR documents the types of files we have in the code base. While there, also update the directory structure docs.
=> Update docs on directory structure and file types

.github/workflows/docker_prebuilt_4c.yml, docker/prebuilt_4C/Dockerfile, docker/prebuilt_4C/README.md
This PR adds a new docker image where 4C is already built. The plan is to create the docker image once the nightly workflow succeeds. Since we do not have versioning yet, the image is always tagged as `latest`. This docker image can be used in Actions where a 4C build is required or for users who want to quickly check out 4C without needing to build it themselves.
~~This is a first draft as I wanted to get your feedback first, before rebuilding the `4c-dependencies` image because I moved a Dockerfile.~~
The Dockerfile for the dependencies image has been moved to a separate folder in #112. The Dockerfile to build 4c is added to the new folder `prebuilt_4C`.
The pre-built 4C docker image just uses the `4c-dependencies-ubuntu24.04` image out of convenience for now. Originally, I wanted to …
=> Add docker image with prebuilt 4c

src/core/fem/src/geometric_search/4C_fem_geometric_search_utils.hpp
=> Add a missing MPI include when ArborX is off

presets/lnm/workstation/CMakePresets.json
Alternative to #116 
Since the LLVM installation is not able to bring a new `libstdc++` required for newer C++ standards, @amgebauer and I decided to provide a newer GCC for now.
Related to #65
=> Update LNM default compiler to GCC 13.2

.github/workflows/docker.yml, .github/workflows/docker_prebuilt_4c.yml
Only push docker images in workflows when they are run from the base repo. Otherwise, the actions in forks will fail because forks are not allowed to push to our registry. 
Also, fix a missing path in the docker workflow trigger. When the `docker/dependencies/` folder contains changes the latest image should also be updated.
=> Only push docker images in workflows when they are run from the base repo

src/mat/4C_mat_inelastic_defgrad_factors.cpp, src/mat/4C_mat_inelastic_defgrad_factors.hpp, src/mat/4C_mat_inelastic_defgrad_factors_service.hpp, src/mat/vplast/4C_mat_vplast_law.hpp, src/mat/vplast/4C_mat_vplast_reform_johnsoncook.cpp, src/mat/vplast/4C_mat_vplast_reform_johnsoncook.hpp, unittests/mat/4C_inelastic_defgrad_factors_test.cpp, unittests/mat/vplast/4C_vplast_reform_johnsoncook_test.cpp
The implementation of substepping in the time integration of InelasticDefgradTransvIsotropElastViscoplast currently uses try-catch mechanisms, with explicit throwing of exceptions to trigger a new substep. As discussed in [2646](https://gitlab.lrz.de/baci/baci/-/merge_requests/2646#note_3454413), it is desirable to avoid this type of mechanism. Moreover, simulations using the current implementation have shown various convergence problems and "random" overflow errors. This PR addresses the issues outlined herein. Specifically, the following work was performed:
- Categorized the types of errors that can be encountered in the time integration, and in the additional stiffness calculation (contribution to the global linearization).
- Removed the try-catch handling and improved the substepping …
=> Improve substepping implementation in InelasticDefgradTransvIsotropElastViscoplast

.github/actions/merge_junit_report_artifacts/action.yml, .github/workflows/buildtest.yml, .github/workflows/nightly_tests.yml
Export a combined junit test report after testing.
This lets us easily extract the runtime of the test suite. We can use this to automatically chunk the test suite (see #129).
=> Add combined junit test report published as artifact

.github/workflows/buildtest.yml
`gcc13_assertions_test_report` is skipped on the main branch. It should not be checked in `ensure_all_tests_pass`.
Follows #9.
=> Allow skipped gcc13_assertions_test_report

.github/workflows/buildtest.yml
Running this job on `main` comes with the burden that we need to maintain the list of jobs that might be skipped.
We only need this job in PRs, so we can skip in on main.
=> Skip `ensure_all_tests_pass` on main

src/mat/4C_mat_inelastic_defgrad_factors.cpp, src/mat/4C_mat_inelastic_defgrad_factors.hpp, src/mat/4C_mat_inelastic_defgrad_factors_service.hpp
This PR implements a quick fix for the redundant material evaluations issue #121, specifically for the transversely isotropic material `InelasticDefgradTransvIsotropElastViscoplast`. Concretely, the deformation gradient, which is the input of the material evaluations, is tracked continuously. If an inelastic deformation gradient has been previously computed for a specific deformation gradient, then the solution is simply returned, instead of repeating the substepping scheme (which would yield the exact same result). A performance speed up of approx. 2 was reached with this quick fix in the exemplary simulations performed. I am aware that this quick fix is not the optimal solution. However, it is IMO the best approach until we can find a consistent solution for all materials, see issue …
=> Quick fix for the material evaluate calls in the case of InelasticDefgradTransvIsotropElastViscoplast

src/core/io/src/4C_io_discretization_visualization_writer_mesh.cpp
For now, the case that multiple unique strings are provided to `DiscretizationVisualizationWriterMesh::append_result_data_vector_with_context` via the context object is only supported for DOF based output. This PR adds an error if multiple unique strings are provided for element and node based output.
=> Add error on not supported output case

.github/actions/chunk_test_suite/action.yml, .github/actions/download_4C_build/action.yml, .github/workflows/coverage.yml, .github/workflows/deploy.yml, .github/workflows/documentation.yml, cmake/setup_global_options.cmake, presets/docker/CMakePresets.json
This PR adds LLVM source based coverage (cf. https://clang.llvm.org/docs/SourceBasedCodeCoverage.html).
It is **much faster** than the coverage report that we used to have. In my fork, it finishes within 2h15m. I have a pro account with 40 parallel runners, so testing might take a bit longer within 4C-multiphysics, but I expect it to be below 3h.
The report itself is also a bit different:
:heavy_check_mark:  Optimization does not affect coverage (we can use normal optimization)
:heavy_check_mark: We see coverage for each instantiation of a template (i.e., we see which instantiations are covered, which not, optional, could be disabled if too much)
:heavy_check_mark: For every execution branch bifurcation (e.g., an `if`-statement) we see the percentage how often a branch was taken
:x: We …
=> Add LLVM source-based coverage report generated every night

.github/workflows/coverage.yml
For the coverage workflow, we ran into problems concerning disk storage (see https://github.com/4C-multiphysics/4C/actions/runs/12308399500). Thus, the number of chunks is increased from 40 to 60, resulting in less output data per runner, which resolved the issue on my fork.
Closes #155 
Follows https://github.com/4C-multiphysics/4C/pull/128
=> Increase number of chunks for coverage workflow

.github/workflows/coverage.yml, README.md
Adds the coverage badges to our README.
I also change the coverage color so that it is consistent with our previous colors.
* 0-75: red
* 75-90: orange
* 90-100: green
=> Add coverage badge to README

src/core/comm/src/4C_comm_pack_buffer.hpp
We can resize the destination buffer and `memcpy` in there directly, thus, saving a copy operation.
This also fixes a warning seen in #130, although I am not exactly sure why.
=> PackBuffer: avoid an additional copy of data

.github/ISSUE_TEMPLATE/config.yml
Following #166 , this PR adds a new option people see when creating an issue. With the [template chooser](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#configuring-the-template-chooser) config, a link to the Github Discussions is added for questions, help or support requests. See for example, [numpy](https://github.com/numpy/numpy/issues/new/choose) how this looks like.
Thanks, @gilrrei, for telling me about this feature.
=> Add link to Discussions for issue template chooser

src/core/io/src/4C_io_input_parameter_container.cpp, src/core/io/src/4C_io_input_parameter_container.hpp, src/core/io/src/4C_io_input_spec.cpp, src/core/io/src/4C_io_input_spec.hpp, src/core/io/src/4C_io_input_spec_builders.cpp, src/core/io/src/4C_io_input_spec_builders.hpp, src/core/io/src/4C_io_linedefinition.cpp, src/core/io/tests/4C_io_input_spec_test.cpp, src/core/io/tests/4C_io_linedefinition_test.cpp
To progress with #73 and merge our two input definitions, we need an implementation that can handle all the cases the two competing implementations have. This PR proposes this implementation. The main design goal is to have an easily readable and flexible way to construct input lines (as known from .dat format), while keeping in mind that we also want to support other formats soon (mainly yaml). In its most concise form, a line may now be written like this (see also the unit tests):
```cpp
auto input = group({
entry<int>("a", {.default_value = 42}),
one_of({
entry<double>("b"),
group("nested",
{
entry<std::string>("c"),
entry<double>("d"),
}),
}),
});
```
This is a very concise style without any unnecessary clutter. Of course, this is still C++ and you can also name all the types very …
=> Reimplement LineDefinition as a more powerful InputSpec

.pre-commit-config.yaml, .typos.toml, apps/create_rtdfiles/4C_create_rtdfiles_utils.hpp, apps/global_full/4C_global_full_cal_control.cpp, apps/global_full/4C_global_full_main.cpp, apps/post_monitor/4C_post_monitor.cpp, apps/post_monitor/4C_post_monitor.hpp, apps/post_processor/4C_post_processor_single_field_writers.cpp, apps/pre_exodus/4C_pre_exodus.cpp, apps/pre_exodus/4C_pre_exodus_readbc.cpp, apps/pre_exodus/4C_pre_exodus_readbc.hpp, apps/pre_exodus/4C_pre_exodus_reader.hpp, apps/pre_locsys/4C_pre_locsys.cpp, src/thermo/4C_thermo_dyn.cpp, src/thermo/4C_thermo_dyn.hpp
Typos are annoying to fix during review (if they are even detected there). Luckily, there is [typos](https://github.com/crate-ci/typos), a configurable and fast spell checker specifically written for code bases. This PR enables `typos` in the pre-commit hooks. I suggest going over the different file types we have and start enforcing the check.
Special words that we do not want to be corrected are listed in `.typos.toml`. For now, I only applied the check to parts of the C++ sources to find the special cases we need to ignore. Of course, we could also fix some of these cases in the future.
=> Introduce typos hook

src/mat/4C_mat_inelastic_defgrad_factors.cpp, src/mat/4C_mat_inelastic_defgrad_factors.hpp, src/mat/vplast/4C_mat_vplast_reform_johnsoncook.cpp, unittests/mat/4C_inelastic_defgrad_factors_test.cpp, unittests/mat/vplast/4C_vplast_reform_johnsoncook_test.cpp
The PR fixes a previously undetected error related to the utilized time step in the unit tests of `InelasticDefgradTransvIsotropElastViscoplast` and `ReformulatedJohnsonCook`. Specifically, it avoids the evaluation of log(0.0), as was previously the case. The failing unit tests were detected by  @c-p-schmidt while working on other files, not associated to the mentioned classes. @c-p-schmidt : thanks for reporting them! Moreover, the variable `check_dt` was removed, as it is not necessary in the updated overflow error checking anymore.
=> Fix unit tests for transversely isotropic viscoplastic material

README.md
Remove a warning, that is more or less outdated.
=> Remove warning about migration to GitHub

.clang-tidy, src/core/comm/src/4C_comm_pack_buffer.hpp, src/core/comm/src/4C_comm_pack_helpers.hpp, src/core/fem/src/general/utils/4C_fem_general_utils_gauss_point_extrapolation.cpp, src/core/fem/src/general/utils/4C_fem_general_utils_integration.hpp, src/core/io/src/4C_io_input_spec_builders.hpp, src/core/io/src/4C_io_string_converter.hpp, src/core/utils/src/functions/4C_utils_symbolic_expression.cpp, src/core/utils/src/numerics/4C_utils_fad.hpp, src/core/utils/src/numerics/4C_utils_mathoperations.hpp, src/core/utils/src/numerics/4C_utils_mathoperations_cln.hpp, src/core/utils/src/numerics/4C_utils_mathoperations_sacado.hpp, src/core/utils/src/stl_extension/4C_utils_singleton_owner.hpp, src/solid_3D_ele/4C_solid_3D_ele_calc.cpp, src/solid_3D_ele/4C_solid_3D_ele_interface_serializable.hpp, src/solid_scatra_3D_ele/4C_solid_scatra_3D_ele_calc.cpp
Use the more expressive and powerful C++ 20 `requires` syntax instead of `std::enable_if`. I applied it to all code in the core module and some places that use the same concepts. I also added the case style for concepts to our `clang-tidy` config.
=> Replace SFINAE in core with C++20 concepts

src/core/io/src/4C_io_elementreader.cpp, src/core/io/src/4C_io_gridgenerator.cpp, src/core/io/src/4C_io_input_file_utils.cpp, src/core/io/src/4C_io_input_file_utils.hpp, src/core/io/src/4C_io_linedefinition.cpp, src/core/io/src/4C_io_linedefinition.hpp, src/core/utils/src/functions/4C_utils_function.cpp, src/core/utils/src/functions/4C_utils_function.hpp, src/core/utils/src/functions/4C_utils_function_library.cpp, src/core/utils/src/functions/4C_utils_function_manager.cpp, src/core/utils/src/functions/4C_utils_function_manager.hpp, src/core/utils/src/functions/4C_utils_function_of_time.cpp, src/core/utils/src/functions/4C_utils_function_of_time.hpp, src/core/utils/src/functions/4C_utils_functionvariables.cpp, src/core/utils/src/functions/4C_utils_functionvariables.hpp, src/core/utils/src/result_test/4C_utils_result_test.cpp, src/core/utils/src/result_test/4C_utils_result_test.hpp, src/fluid/4C_fluid_functions.cpp, src/fluid_xfluid/4C_fluid_xfluid_functions.cpp, src/fluid_xfluid/4C_fluid_xfluid_functions_combust.cpp, src/global_data/4C_global_data_read.cpp, src/poromultiphase_scatra/4C_poromultiphase_scatra_function.cpp, src/structure_new/src/utils/4C_structure_new_functions.cpp
Further unifies the different input mechanisms #73. `LineDefinition` could be replaced by `InputSpec` now.
=> Use InputParameterContainer instead of LineDefinition to pass input parameters

apps/create_rtdfiles/4C_create_rtdfiles_utils.cpp, apps/global_full/4C_global_full_main.cpp, src/contact_constitutivelaw/4C_contact_constitutivelaw_valid_laws.cpp, src/contact_constitutivelaw/4C_contact_constitutivelaw_valid_laws.hpp, src/core/io/src/4C_io_input_spec.cpp, src/core/io/src/4C_io_input_spec.hpp, src/core/io/src/4C_io_input_spec_builders.cpp, src/core/io/src/4C_io_input_spec_builders.hpp, src/core/io/src/4C_io_linedefinition.cpp, src/core/io/tests/4C_io_input_spec_test.cpp, src/global_data/4C_global_data_read.cpp, src/mat/4C_mat_materialdefinition.cpp, src/mat/4C_mat_materialdefinition.hpp
This PR shuffles code around such that the `4C_io_input_spec.hpp` header contains barely enough information to pass `InputSpec` around by value and call a few central functions. All implementation details that are necessary for construction are still hidden in `4C_io_input_spec_builders.hpp`. It is now obvious when code uses the implementation details because it calls `impl()`. This is currently required when interfacing with the legacy input mechanism and the rtd emitter.
=> Reorganize InputSpec headers

src/particle_rigidbody/4C_particle_rigidbody.cpp
Fixes a warning I get when compiling `-O3` w/o assertions with GCC 13.2 installed via Spack (aka LNM release config). At least the code also becomes simpler this way.
Side note: this once more shows that we will need patches for releases ;) It was just a coincidence that I noticed this warning and it would have almost made it into the release.
=> Fix a false positive gcc warning in particles

apps/global_full/4C_global_full_control.cpp, src/core/comm/src/4C_comm_mpi_utils.hpp, src/core/comm/src/4C_comm_pack_helpers.hpp, src/core/io/src/4C_io_domainreader.cpp, src/core/io/src/4C_io_elementreader.cpp, src/core/io/src/4C_io_input_file.cpp, src/core/io/src/4C_io_input_file.hpp, src/core/io/src/4C_io_nodereader.cpp, src/core/io/tests/4C_io_input_file_test.cpp, src/global_data/4C_global_data_read.cpp, src/particle_engine/4C_particle_engine_particlereader.cpp
This PR fixes a problem where huge yaml files containing a huge discretization cannot be read effectively when using many MPI ranks. Input is now read like this, independent of the underlying format:
- Read the complete input file (+ any includes) on rank 0
- Determine huge sections (more than 10,000 entries)
- Communicate everything except the huge sections to all ranks.
- If a huge section is requested on a rank > 0, communicate it then. This means that `lines_in_section` must be a collective call. To support reading on rank 0 only, we now have `lines_in_section_rank_0_only`. Note that this distinction existed before as well but is now made explicit in the function names.
This implementation is much simpler than the on-the-fly reading we had previously. It seems reasonable that the …
=> InputFile determines huge sections automatically

.github/workflows/docker.yml, .github/workflows/docker_prebuilt_4c.yml
`latest` should refer to the latest release
`main` will be used for the current `main` branch.
=> Tag docker images as main instead of latest

apps/pre_exodus/4C_pre_exodus.cpp
Probably since the change in keywords (renaming PROBLEM TYP to PROBLEM TYPE), `pre_exodus` did not procude a correct `default.head` for the case that the option `--head` is missing. (The complete part after `PROBLEM SIZE` was skipped).
I changed a few lines, so that now the complete `default.head` is printed as it should. In addition, now the correct output does not depend on the number of dashes in front of the section keyword anymore ;-)
Follow up to https://gitlab.lrz.de/baci/baci/-/merge_requests/2645
=> Fix bug in default.head creation by pre_exodus

.github/actions/build_4C/action.yml, .github/workflows/buildtest.yml
We only have limited amount of storage available for our cache. Since we build clang18 anyway in the stage before, we can reuse the cache from that stage and don't need our own.
fyi @vryy
=> Reuse ccache from clang18_build for clang18_install_test

src/contact_constitutivelaw/4C_contact_constitutivelaw_valid_laws.cpp, src/core/io/src/4C_io_input_spec.cpp, src/core/io/src/4C_io_input_spec.hpp, src/core/io/src/4C_io_input_spec_builders.cpp, src/core/io/src/4C_io_input_spec_builders.hpp, src/core/io/src/4C_io_linedefinition.cpp, src/core/io/tests/4C_io_input_spec_test.cpp, src/mat/4C_mat_materialdefinition.cpp
This PR allows to call `emit_metadata` for an `InputSpec` which will write all the knowledge we have about that spec into a yaml file. We do not yet use it for the `4C_metadata.yaml` file but this can follow soon if we agree this format looks sensible in general.
Part of #113, Depends on #237 
FYI @gilrrei
=> Emit metadata for InputSpec

src/structure_new/src/explicit/4C_structure_new_expl_centrdiff.cpp
Resetting the step should only be done if the timestep will be recomuted again (e.g. for time adaptivity) and not in the general case when setting the state.
=> Don't reset step in explicit central difference scheme

src/contact/4C_contact_nitsche_integrator_ssi_elch.cpp, src/scatra_ele/4C_scatra_ele_boundary_calc_elch_electrode.cpp, src/scatra_ele/4C_scatra_ele_boundary_calc_elch_electrode_sti_thermo.cpp, src/scatra_ele/4C_scatra_ele_boundary_calc_sti_electrode.cpp, src/solid_3D_ele/4C_solid_3D_ele_calc_lib.hpp
Now, `so3_utils` can be removed with `so3`.
=> Remove dependencies to so3_utils in other modules

apps/create_rtdfiles/4C_create_rtdfiles_utils.cpp, apps/global_full/4C_global_full_control.cpp, apps/global_full/4C_global_full_main.cpp, apps/pre_exodus/4C_pre_exodus.cpp, src/core/fem/src/general/utils/4C_fem_general_utils_createdis.cpp, src/core/fem/src/general/utils/4C_fem_general_utils_createdis.hpp, src/core/io/src/4C_io_input_file_utils.cpp, src/core/io/src/4C_io_input_file_utils.hpp, src/core/utils/src/functions/4C_utils_function_library.cpp, src/core/utils/src/functions/4C_utils_function_manager.cpp, src/core/utils/src/functions/4C_utils_function_manager.hpp, src/core/utils/src/result_test/4C_utils_result_test.cpp, src/core/utils/src/result_test/4C_utils_result_test.hpp, src/fluid/4C_fluid_functions.cpp, src/fluid_xfluid/4C_fluid_xfluid_functions.cpp, src/fluid_xfluid/4C_fluid_xfluid_functions_combust.cpp, src/global_data/4C_global_data_read.cpp, src/global_legacy_module/4C_global_legacy_module.cpp, src/module_registry/4C_module_registry_callbacks.hpp, src/poromultiphase_scatra/4C_poromultiphase_scatra_function.cpp, src/structure_new/src/utils/4C_structure_new_functions.cpp
`LineDefinition` is only a wrapper around `InputSpec` with reduced functionality. This PR replaces its use for
- cloning material map
- result description
- functions
I will replace the element definition in another PR.
Part of #73
=> Replace most LineDefinitions with InputSpecs

apps/create_rtdfiles/4C_create_rtdfiles_utils.cpp, apps/create_rtdfiles/4C_create_rtdfiles_wrapper.cpp, apps/global_full/4C_global_full_main.cpp, apps/pre_exodus/4C_pre_exodus.cpp, src/core/fem/src/general/element/4C_fem_general_element_definition.cpp, src/core/io/src/4C_io_input_file_utils.cpp, src/core/io/src/4C_io_input_spec.cpp, src/core/io/src/4C_io_input_spec.hpp, src/core/io/src/4C_io_input_spec_builders.cpp, src/core/io/src/4C_io_input_spec_builders.hpp, src/core/io/tests/4C_io_input_spec_test.cpp, src/global_data/4C_global_data_read.cpp, src/global_legacy_module/4C_global_legacy_module.cpp, src/global_legacy_module/4C_global_legacy_module_validmaterials.cpp, src/global_legacy_module/4C_global_legacy_module_validmaterials.hpp, src/mat/4C_mat_materialdefinition.cpp, src/module_registry/4C_module_registry_callbacks.hpp
This PR uses `InputSpec` for  the possible materials on a higher level than before. My goal is to only use InputSpec for all input parameter related tasks, see #73. While there, I improved the dat comments. The valid materials are extracted to the global legacy module. 
Part of #59
=> Extract valid materials to global legacy module and streamline input

src/core/fem/src/condition/4C_fem_condition_definition.cpp, src/core/io/src/4C_io_domainreader.cpp, src/core/io/src/4C_io_elementreader.cpp, src/core/io/src/4C_io_input_file.cpp, src/core/io/src/4C_io_input_file.hpp, src/core/io/src/4C_io_input_file_utils.cpp, src/core/io/src/4C_io_nodereader.cpp, src/core/io/tests/4C_io_input_file_test.cpp, src/core/utils/src/functions/4C_utils_function_manager.cpp, src/global_data/4C_global_data_read.cpp, src/particle_engine/4C_particle_engine_particlereader.cpp
We used to convert every input fragment into a dat-style string, even if it came from yaml. This PR prepares for a change in the internals of the input mechanism, such that we always match our expectation (InputSpec) against the content (InputFile::Fragment) and receive the parameters (InputParameterContainer) without doing unnecessary conversion to a format that is less powerful. We can still read both formats. This PR does not change the timings for a 1e6 element input file for .dat or .yaml.
My overall vision is to have the following two functions which all (parameter) input/output will be going through:
```
// reading input (added in this PR)
InputFile::Fragment::match(InputSpec) -> InputParameterContainer
// wrtiting into an input file
InputFile::append(InputSpec, …
```
=> InputFile::Fragment to access input file content independent of underlying format

src/core/utils/src/functions/4C_utils_function.cpp, src/core/utils/src/functions/4C_utils_function_library.cpp, src/core/utils/src/functions/4C_utils_function_manager.cpp, src/core/utils/src/functions/4C_utils_function_of_time.cpp, src/core/utils/src/functions/4C_utils_functionvariables.cpp
As described in #73, the `tag()` function is rather questionable as we nowadays have better ways to describe input, e.g. `group()`, `one_of` and `selection`. This PR removes the tags from the functions. Note that I favored backward-compatibility and only performed restructuring that does not break existing files.
=> Remove input tag() in functions

src/membrane/4C_membrane_evaluate.cpp, src/structure/4C_structure_timint.cpp, src/structure/4C_structure_timint.hpp, src/structure_new/src/4C_structure_new_elements_paramsinterface.hpp, src/structure_new/src/model_evaluator/4C_structure_new_model_evaluator_data.cpp, src/structure_new/src/model_evaluator/4C_structure_new_model_evaluator_data.hpp
While working on some vtk-based output inside the new structure time integration I realized that the membrane output in the old time integration is unused. Thus removing it as a preparatory step for the vtk-based output.
Related to #211
=> Remove output of membrane thickness from old structure time integration

apps/global_full/4C_global_full_main.cpp, src/core/io/src/4C_io_input_file_utils.cpp, src/core/io/src/4C_io_input_file_utils.hpp, src/core/io/src/4C_io_input_spec.cpp, src/core/io/src/4C_io_input_spec_builders.cpp, src/core/io/src/4C_io_input_spec_builders.hpp, src/core/io/tests/4C_io_input_spec_test.cpp, src/global_legacy_module/4C_global_legacy_module.cpp, src/global_legacy_module/4C_global_legacy_module.hpp
Part of #113 
Includes a few of the more complicated input file sections. The remaining ones need a little bit of polishing and simplification to be as easy to add.
Draft as I will iterate over this state with @gilrrei to see which (more or less arbitrary) structure makes the most sense for our 4C_metadata.yaml.
=> Provide more input metadata for schema generation

src/core/io/src/4C_io_input_spec_builders.cpp, src/core/io/src/4C_io_input_spec_builders.hpp, src/core/io/tests/4C_io_input_spec_test.cpp
- `all_of` uses its own internal implementation: this makes `GroupSpec` easier to handle as the previously unnamed `all_of` case moved into `AllOfSpec`.
- nested `one_of`s are now also flattened into parent `one_of`, same as `all_of`s are
=> Minor enhancements to all_of and one_of

CITATION.cff
This adds a CITATION.cff file to the repo. GitHub recognizes the file and shows it on the sidebar:
see https://github.com/amgebauer/4C
=> Add CITATION.cff to the repository

src/core/io/src/4C_io_input_file.cpp, src/core/io/src/4C_io_input_spec.cpp, src/core/io/src/4C_io_input_spec.hpp, src/core/io/src/4C_io_input_spec_builders.cpp, src/core/io/src/4C_io_input_spec_builders.hpp, src/core/io/src/4C_io_yaml.cpp, src/core/io/src/4C_io_yaml.hpp, src/core/io/tests/4C_io_input_spec_test.cpp
As promised in #316, this PR implements useful error messages for yaml input. Here are some examples:
```
Could not match this input
MAT: 1
MAT_ElastHyper:
NUMMAT: 1
MATIDS: 10
DENS: 0.1
against the given input specification. This was the best attempt to match the input:
{
Fully matched entry 'MAT'
Expected exactly one of a few choices but matched:
Partially matched group 'MAT_ElastHyper'
Fully matched entry 'NUMMAT'
Partially matched entry 'MATIDS' (expected type 'vector<int>' did not validate)
}
```
or
```
Could not match this input
MAT: 1
MAT_ElastHyper:
NUMMAT: 1
MATIDS: [10]
DENS: 0.1
ELAST_CoupNeoHooke:
YOUNG: 10
NUE: 0.25
against the given input specification. This was the best attempt to match the input:
{
Fully matched entry 'MAT'
Expected exactly one but matched multiple:
Fully …
```
=> Implement user-friendly yaml error handling

src/core/io/src/4C_io_input_spec_builders.hpp, src/core/io/tests/4C_io_input_spec_test.cpp, src/global_legacy_module/4C_global_legacy_module_validmaterials.cpp, src/mat/4C_mat_muscle_combo.cpp, src/mixture/4C_mixture_rule_map.cpp
Instead of hooking deeply into the `InputSpec` mechanism with `user_defined`, let users attach `on_parse` callbacks to entries. 
Implemented on top of #320, will be rebased.
=> Remove InputSpecBuilders::user_defined

.github/dependabot.yml
I believe some of our CI actions are outdated. Let's enable `dependabot` (https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/about-dependabot-version-updates) to ensure we stay up-to-date with minimal manual effort.
=> Github: enable dependabot updates for actions

src/core/io/src/4C_io_input_spec_builders.hpp, src/core/io/src/4C_io_yaml.hpp, src/core/io/tests/4C_io_input_spec_test.cpp
Also fix a small bug where selection prints the wrong value for enum classes.
=> InputSpec: clearly state supported types for input

src/core/fem/src/general/element/4C_fem_general_element_integration.hpp, src/core/fem/src/general/utils/4C_fem_general_utils_gausspoints.hpp, src/core/fem/tests/general/4C_fem_general_element_integration_test.cpp, src/so3/4C_so3_poro.cpp, src/solid_3D_ele/4C_solid_3D_ele_calc.cpp, src/solid_3D_ele/4C_solid_3D_ele_calc_lib.hpp, src/solid_3D_ele/4C_solid_3D_ele_calc_lib_integration.hpp, src/solid_3D_ele/4C_solid_3D_ele_neumann_evaluator.cpp, src/solid_poro_3D_ele/4C_solid_poro_3D_ele_calc_pressure_based.cpp, src/solid_poro_3D_ele/4C_solid_poro_3D_ele_calc_pressure_velocity_based.cpp, src/solid_scatra_3D_ele/4C_solid_scatra_3D_ele_calc.cpp
This PR adds some utility functions for integrating over any celltype in core.
These functions are similar to that what we also have in the new solid elements. I just generalized them a bit, so that they are not connected to solids, and can also handle manifolds (e.g., a surface in the 3d space).
I will use this in another PR to extract the spring-dashpots from so3_surface.
I will also reuse this in the new solid elements, but I want to keep the changes in here small.
=> Create some basic utility functions to integrate over a celltype in any dimension

src/core/io/src/4C_io_yaml.cpp, src/core/io/src/4C_io_yaml.hpp
Although it would be great to only support `true` and `false` as boolean values, the input files are not in this state. However, we always emit the pretty values. Once we have automatic conversion between file formats, all the messy values will be cleaned up over time.
=> Allow reading a few more values as bools from yaml files

doc/readthedocs/4Csetup.rst, tests/input_files/mat_iso_viscoplast_refJC_log_substep.dat, tests/input_files/mat_transviso_viscoplast_refJC_log_substep.dat, tests/input_files/mat_transviso_viscoplast_refJC_standard_substep.dat
Whilst reading the installation process, I stumbled upon *Chair of Computational Mechanics*, but the LNM publishes under *Institute for Computational Mechanics*
@dragos-ana FYI I changed some files where your master's thesis is referenced
=> Change LNM name

src/adapter/4C_adapter_str_structure.cpp, src/adapter/4C_adapter_str_structure_new.cpp, src/core/io/src/4C_io_input_file_utils.cpp, src/fluid/4C_fluid_implicit_integration.cpp, src/fsi/src/partitioned/4C_fsi_partitioned.cpp, src/inpar/4C_inpar_IO_monitor_structure_dbc.cpp, src/inpar/4C_inpar_IO_monitor_structure_dbc.hpp, src/inpar/4C_inpar_fluid.cpp, src/inpar/4C_inpar_fluid.hpp, src/red_airways/4C_red_airways_implicitintegration.cpp, src/structure_new/src/utils/4C_structure_new_monitor_dbc.cpp, src/structure_new/src/utils/4C_structure_new_timint_basedataio_monitor_dbc.cpp, src/thermo/src/4C_thermo_adapter.cpp
This call only works when you attach an EntryValidator for an entry beforehand. Previously, this worked as long as all the parameters came from the global parameter list where these values were set. On the one hand, this will no longer work once I change this part of the input to `InputSpec`. On the other hand, the change in this PR makes sense in isolation to make the respective functions useable without setting up the implicit global state.
This PR removes all occurrences of `Teuchos::getStringValue`.
Related to #339
=> Avoid Teuchos::getStringValue

doc/readthedocs/4Csetup.rst, doc/readthedocs/about.rst, doc/readthedocs/coverage_report.rst, doc/readthedocs/developer_cluster.rst, doc/readthedocs/doxygen.rst, doc/readthedocs/tutorial_contact_3d.md, tests/framework-test/tutorial_contact_3d.md
Changes GitLab mentions and links to GitHub, mainly in the documentation.
I only changed the ones I could find the information on GitHub for. There are more, lots also referencing GitLab runners or old MR, these ones I didn't change.
=> Update links from GitLab to GitHub

doc/readthedocs/4Csetup.rst, doc/readthedocs/developer_cmake.rst
- Information on participating institutes is not required in the description of how to setup 4C.
- Historic remarks and links to GitLab are not required to work with CMake presets.
I came across this through PRs #341, #342
=> Remove obsolete content from documentation

CITATION.cff, README.md, doc/doxygen/index.doc, doc/readthedocs/about.rst, doc/readthedocs/index.rst, doc/readthedocs/materials.rst
So far we had an inconsistent naming of multiphysics, i.e., multiphysics and multi-physics. This inconsistency is now resolved.
https://github.com/4C-multiphysics/website/pull/14
https://github.com/4C-multiphysics/website/issues/13
=> Consistent naming of multiphysics

src/core/io/src/4C_io_input_spec_builders.hpp, src/core/io/tests/4C_io_input_spec_test.cpp
Essentially the same fix as in 4692c3e4cfdf4ec656fea1b40d6eafcceb4ddea0 but this time for dat parameters.
Side note: I think the code duplication in this PRs shows that I can probably restructure the internals of `InputSpecBuilders` a bit more.
=> Fix a parser bug for single defaulted dat params

src/core/io/src/4C_io_input_spec_builders.cpp, src/core/io/src/4C_io_input_spec_builders.hpp, src/core/io/tests/4C_io_input_spec_test.cpp, src/core/utils/src/string_utils/4C_utils_string.cpp, src/core/utils/tests/string_utils/4C_utils_string_test.cpp
Another fix to get #343 working (maybe the last one :crossed_fingers:). Some parameters have line breaks in their descriptions but these don't make a ton of sense in a one-liner dat description of a parameter.
=> Trim descriptions when printing to dat comments

src/core/io/src/4C_io_input_spec_builders.cpp, src/core/io/src/4C_io_input_spec_builders.hpp
Catch unprintable characters, notably `\f`, early.
FYI @gilrrei @ischeider
=> Input: ensure printable names and descriptions

src/core/io/src/4C_io_input_parameter_container.cpp, src/core/io/src/4C_io_input_parameter_container.hpp, src/core/io/src/4C_io_input_spec.cpp, src/core/io/src/4C_io_input_spec_builders.cpp, src/core/io/src/4C_io_input_spec_builders.hpp, src/core/io/tests/4C_io_input_parameter_container_test.cpp, src/core/io/tests/4C_io_input_spec_test.cpp
This is the missing link to treat the full input file structure (except the geometry sections) as a single InputSpec.
=> Add InputSpecBuilders::list()

src/core/io/src/4C_io_input_file_utils.cpp, src/global_legacy_module/4C_global_legacy_module.cpp
Use the new `list` feature to properly describe `MATERIALS`, `FUNCT`, etc. These sections contain multiple entries of the same `InputSpec` and this is exactly what `list` encodes.
@gilrrei Sorry it still does not contain all the sections, but I am working on it.
=> Update metadata file to emit lists

src/core/io/src/4C_io_input_spec_builders.hpp, src/core/io/src/4C_io_value_parser.hpp, src/core/io/src/4C_io_yaml.hpp, src/core/io/tests/4C_io_input_spec_test.cpp, src/core/io/tests/4C_io_value_parser_test.cpp, src/core/utils/src/functions/4C_utils_function.cpp, src/core/utils/src/functions/4C_utils_function_manager.cpp, src/poromultiphase_scatra/4C_poromultiphase_scatra_function.cpp, src/poromultiphase_scatra/4C_poromultiphase_scatra_function.hpp, src/poromultiphase_scatra/4C_poromultiphase_scatra_function_parameters.cpp, src/poromultiphase_scatra/4C_poromultiphase_scatra_function_parameters.hpp, unittests/poromultiphase_scatra/4C_poromultiphase_scatra_function_test.cpp
Replaces `vector<pair<string,T>>` with this more expressive input for yaml. In dat, both are the same.
Note: I deliberately only support string keys for now. In the future, I am open to allowing `int` as well but we are not using this right now. Btw, yaml technically allows arbitrary objects as keys, but I don't think we want this in our code. 
FYI @gilrrei
=> InputSpec: support more expressive map<string,T>

src/structure_new/src/4C_structure_new_integrator.cpp, src/structure_new/src/utils/4C_structure_new_utils.cpp
Without these 2 additional headers the code does not compile with `Trilinos` built in debug mode. The error was here:
```
include/Teuchos_TypeNameTraits.hpp:58:27: error: invalid use of incomplete type ‘class FourC::Core::LinAlg::Solver’
58 |       return demangleName(typeid(T).name());
```
=> Add missing definitions of class `Core::LinAlg::Solver`

src/core/fem/src/general/utils/4C_fem_general_element_dof_matrix.hpp, src/core/fem/tests/utils/4C_fem_general_element_dof_matrix_test.cpp, src/solid_3D_ele/4C_solid_3D_ele_calc_displacement_based.hpp, src/solid_3D_ele/4C_solid_3D_ele_calc_lib.hpp, src/solid_3D_ele/4C_solid_3D_ele_calc_lib_mulf.hpp, src/solid_3D_ele/4C_solid_3D_ele_calc_shell_ans_lib.hpp, src/solid_3D_ele/4C_solid_3D_ele_neumann_evaluator.cpp, unittests/solid_3D_ele/4C_solid_3D_ele_calc_lib_test.cpp
This PR applies the transpose to the displacements in the element dof matrices to reuse core utilities and avoid unnecessary copies.
=> Use transpose of displacements and coordinates to avoid copies and be able to reuse core utilities

src/core/linear_solver/src/method/4C_linear_solver_method_parameters.cpp, src/core/linear_solver/src/method/4C_linear_solver_method_parameters.hpp, src/core/linear_solver/src/preconditioner/4C_linear_solver_preconditioner_muelu.cpp
Originates from a comment in PR #127, will be addressed after merging PR #127.
=> Add const qualifier to nullspace extraction

src/core/io/src/4C_io_input_spec.cpp, src/core/io/src/4C_io_input_spec.hpp, src/core/io/src/4C_io_input_spec_builders.cpp, src/core/io/src/4C_io_input_spec_builders.hpp, src/core/io/tests/4C_io_input_spec_test.cpp
Paves the way towards a `dat` -> `yaml` converter
=> InputSpec can emit data to yaml files

src/core/io/src/4C_io_input_file.cpp, src/core/io/src/4C_io_input_file.hpp, src/core/io/src/4C_io_input_file_utils.cpp, src/core/io/src/4C_io_input_file_utils.hpp, src/core/io/src/4C_io_input_spec_builders.cpp, src/core/io/src/4C_io_input_spec_builders.hpp, src/core/io/tests/4C_io_input_file_test.cpp, src/core/io/tests/4C_io_input_spec_test.cpp, src/global_data/4C_global_data_read.cpp
The first four commits introduce small enhancements to existing `InputSpec` functionality to enable the fifth commit, where `InputSpec` is used more directly in `InputFile`.
Found while working on #382
=> Improvements to input mechanism

src/contact/4C_contact_paramsinterface.hpp, src/inpar/4C_inpar_solver_nonlin.cpp, src/structure_new/src/implicit/4C_structure_new_impl_generic.cpp, src/structure_new/src/implicit/4C_structure_new_impl_generic.hpp, src/structure_new/src/model_evaluator/4C_structure_new_model_evaluator_data.cpp, src/structure_new/src/model_evaluator/4C_structure_new_model_evaluator_data.hpp, src/structure_new/src/model_evaluator/4C_structure_new_model_evaluator_manager.cpp, src/structure_new/src/model_evaluator/4C_structure_new_model_evaluator_manager.hpp
The `Modified` parameter list we internally add to NOX breaks the new structure time integration tests with the current Trilinos development branch. To my knowledge and in-depth search in the input files, these options are not used at all, neither in NOX nor in our own code?!
In addition the `Modified` list is only retrieved once in `get_number_of_modified_newton_corrections()`, but the relevant parameter is never found and thus this function always returns 0 (also based on the coverage report). With this PR I propose to just delete the parameter list and the related function, there's no benefit in keeping it.
Closes #405
=> [NOX] Remove "Modified" parameter list

src/solver_nonlin_nox/4C_solver_nonlin_nox_solver_factory.cpp, src/solver_nonlin_nox/4C_solver_nonlin_nox_solver_singlestep.cpp, src/solver_nonlin_nox/4C_solver_nonlin_nox_solver_singlestep.hpp
With the debug version of Trilinos `StepSolver` crashed attempting to dereference null pointer `innerTests`. Since `innerTests` variable is not used anyway, I just removed it.
=> Remove `innerTests` from `SingleStep` solver

src/core/io/src/4C_io_input_parameter_container.hpp, src/core/io/src/4C_io_input_spec_builders.hpp, src/core/io/src/4C_io_input_types.hpp, src/core/io/src/4C_io_value_parser.hpp, src/core/io/src/4C_io_yaml.cpp, src/core/io/src/4C_io_yaml.hpp, src/core/io/tests/4C_io_input_spec_test.cpp, src/core/io/tests/4C_io_value_parser_test.cpp, src/xfem/4C_xfem_xfluid_timeInt.cpp, src/xfem/4C_xfem_xfluid_timeInt.hpp
The initial implementation only contained vectors of primitive types. This PR extends this to allow nested vectors and maps, either with dynamic sizes, fixed sizes, or the dat-style size read from another parameter (the `NUMxxx` parameters).
=> InputSpec: allow for arbitrarily nested vectors and maps

src/core/io/src/4C_io_input_parameter_container.cpp, src/core/io/src/4C_io_input_parameter_container.hpp, src/core/io/src/4C_io_input_parameter_container.templates.hpp, src/core/io/src/4C_io_input_spec_builders.hpp, src/core/io/tests/4C_io_input_parameter_container_test.cpp, unittests/mat/4C_electrode_test.cpp, unittests/mat/4C_inelastic_defgrad_factors_test.cpp
The `InputParameterContainer` was the most expensive include due to the transitive include of `Teuchos::ParameterList`. I moved the `add` method to a `.templates.hpp` which we rarely need to include since we mostly want to `get()`.
=> Extract InputParameterContainer::add to own header

src/core/io/src/4C_io_input_spec_builders.hpp, src/core/io/src/4C_io_yaml.cpp, src/core/io/src/4C_io_yaml.hpp, src/core/io/tests/4C_io_input_spec_test.cpp
This will help to distinguish `yes` from `"yes"`, where the former is a bool and the latter a string in yaml.
FYI @gilrrei
=> Quote string values and descriptions in yaml

.github/workflows/nightly_tests.yml
This PR proposes to write out the build time trace in the nightly clang build. For a useful overview, the results are aggregated with `ClangBuildAnalyzer` (https://github.com/aras-p/ClangBuildAnalyzer). I've been using this tool locally to move critical includes that can cut down compile time drastically. To make the process easier and more accessible, we can now look at the relevant information as part of the actions, see e.g. here https://github.com/sebproell/4C/actions/runs/13465801401/job/37631531951#step:6:13.
=> Record compile time tracing in nightly tests

src/adapter/4C_adapter_coupling_nonlin_mortar.cpp, src/core/comm/src/4C_comm_utils.cpp, src/core/io/src/4C_io_pstream.cpp, src/cut/4C_cut_combintersection.cpp, src/cut/4C_cut_levelsetintersection.cpp, src/cut/4C_cut_levelsetintersection.hpp, src/levelset/4C_levelset_intersection_utils.cpp, src/mortar/4C_mortar_interface.cpp, src/mortar/4C_mortar_strategy_base.cpp, src/mortar/4C_mortar_strategy_factory.cpp, src/mortar/4C_mortar_strategy_factory.hpp, src/structure_new/src/4C_structure_new_timint_basedataglobalstate.cpp, src/structure_new/src/model_evaluator/4C_structure_new_model_evaluator_data.cpp, src/structure_new/src/model_evaluator/4C_structure_new_model_evaluator_data.hpp, src/xfem/4C_xfem_multi_field_mapextractor.cpp, tests/cut_test/cut_test_main.cpp, unittests/geometry_pair/4C_geometry_pair_line_to_volume_segmentation_test.cpp
The 4C build fails when compiling with intel-mpi. This PR fixes the build errors.
- In some places the MPI_COMM was initialized with or assigned a `nullptr`. This works for openmpi as MPI_COMM is a pointer. But for intel-mpi MPI_COMM is an int. Therefore, the nullptr is replaced by the implementation-independent `MPI_COMM_NULL`.
- With MPI_COMM as int, there were two constructors with the same argument types. I removed one of them. The removed constructor was only used in tests.
- I also fixed a bug where only one process would hit an MPI barrier.
=> Fix MPI_COMM nullptr

src/core/io/src/4C_io_input_spec_builders.hpp, src/core/io/src/4C_io_input_types.hpp, src/core/io/tests/4C_io_input_spec_test.cpp, src/core/utils/src/parameters/4C_utils_parameter_list.hpp, src/solid_poro_3D_ele/4C_solid_poro_3D_ele_pressure_based.cpp, src/solid_poro_3D_ele/4C_solid_poro_3D_ele_pressure_velocity_based.cpp, src/solid_poro_3D_ele/4C_solid_poro_3D_ele_utils.hpp
Based on a discussion here: https://github.com/4C-multiphysics/4C/pull/424#issuecomment-2676743683
I have a feeling that the internals of the `selection` implementation can be moved to `EntrySpec` soon. This PR also helped to clarify some types a little more.
=> Enable Noneable in selection

src/core/io/src/4C_io_input_types.hpp, src/core/io/src/4C_io_yaml.hpp, src/core/io/tests/4C_io_input_spec_test.cpp
Fixes ` parameter<Noneable<std::vector<int>>>` which did not work before. Added to test as well.
Required for #437
=> Fix Noneable for containers

src/contact/4C_contact_abstract_data_container.cpp, src/contact/4C_contact_abstract_data_container.hpp, src/contact/4C_contact_abstract_strategy.cpp, src/contact/4C_contact_abstract_strategy.hpp, src/contact/4C_contact_lagrange_strategy.cpp, src/contact/4C_contact_lagrange_strategy.hpp, src/contact/4C_contact_manager.cpp, src/contact/4C_contact_strategy_factory.cpp, src/inpar/4C_inpar_contact.cpp, src/inpar/4C_inpar_contact.hpp
This feature has been added 10 years ago. Today, it is
- unclear what it is supposed to do,
- untested,
- broken with an overflow error.
We have been doing robust contact simulations without for several years, so apparently it is not super important.
All in all, there seems not to be much value in keeping it, so it is removed.
- I looked into this parameter due to #420.
- Closes #422
=> Remove CONTACT_REGULARIZATION

apps/global_full/CMakeLists.txt, cmake/python/requirements.txt, utilities/create_json_schema.py, utilities/metadata_utils.py
This PR enables JSON schemas for all sections
- The python YAML library is changed to ruamel.yaml to allow for YAML 1.2
- The metadata functionality is split into two parts `metadata_utils.py` (creates ptython objects, will also be used for documentation etc) and the script that actually creates the schema
- I used inheritance to keep the dataclasses well interfaced (@sebproell don't worry, in python they are chill)
- Compared to the previous iteration, the script is much more complex. This is due to the fact that all sections are supported now, allowing for nesting information
- This change requires python 3.10, shouldn't be a problem since ubuntu 24.04 will ship with 3.12
To test the schema file, I converted all the .dat input test files to YAML and checked if they were valid. The …
=> Enable all sections in JSON schema

utilities/create_json_schema.py, utilities/metadata_utils.py
All parameter types can be set to `null` if provided by the metadata file.
=> Make all parameter types noneable

src/core/io/src/4C_io_visualization_parameters.cpp, src/core/io/src/4C_io_visualization_parameters.hpp, src/core/io/src/4C_io_visualization_writer_vtu_per_rank.cpp, src/core/io/src/4C_io_visualization_writer_vtu_per_rank.hpp, src/core/io/src/4C_io_vtk_writer_base.cpp, src/core/io/src/4C_io_vtk_writer_base.hpp, src/core/io/src/4C_io_vtu_writer.cpp, src/core/io/src/4C_io_vtu_writer.hpp, src/inpar/4C_inpar_IO_runtime_output.cpp
So far, the compression level of binary runtime vtk output is strictly set to the maximum compression possible in zlib. This PR makes the compression level an optional parameter that can be set in the input file. The default compression level is further changed to the best speed possible in zlib. 
New line in input file:
<pre>
-------------------------------------------------------IO/RUNTIME VTK OUTPUT
OUTPUT_DATA_FORMAT               binary
COMPRESSION_LEVEL                best_compression
</pre>
Options for `COMPRESSION_LEVEL`:
- best_compression (current default)
- best_speed (new default)
- no_compression (probably irrelevant anyways)
The possible speedup when writing output with `best_speed` seems much more advantageous than the smaller output file size achieved with …
=> Add compression level as optional parameter to vtk output

src/beamcontact/4C_beamcontact_beam3contact_manager.cpp, src/inpar/4C_inpar_structure.cpp, src/inpar/4C_inpar_structure.hpp, src/mat/4C_mat_inelastic_defgrad_factors.cpp, src/structure/4C_structure_timint.cpp, src/structure/4C_structure_timint.hpp, src/structure/4C_structure_timint_expl.cpp, src/structure/4C_structure_timint_genalpha.cpp, src/structure/4C_structure_timint_impl.cpp, src/structure/4C_structure_timint_ost.cpp, src/structure_new/src/4C_structure_new_timint_basedataglobalstate.cpp, src/structure_new/src/4C_structure_new_timint_basedatasdyn.cpp, src/structure_new/src/implicit/4C_structure_new_impl_genalpha.cpp, src/structure_new/src/implicit/4C_structure_new_impl_genalpha_liegroup.cpp, src/structure_new/src/implicit/4C_structure_new_impl_ost.cpp, src/structure_new/src/model_evaluator/4C_structure_new_model_evaluator_structure.cpp
- remove obsolete input option (cf. #423)
- convert underlying `enum` to `enum class`
Closes #423
=> Clean-up MASSLIN input parameter

apps/global_full/CMakeLists.txt, cmake/setup_global_options.cmake
Allows to turn off metadata and schema generation in environments where it does not work. It stays on by default.
FYI @ppraegla @tnschmid
=> Add CMake option FOUR_C_ENABLE_METADATA_GENERATION

src/cut/4C_cut_levelsetintersection.cpp
I missed a nullptr for the MPI_COMM. Follow-up to PR #433
=> Fix MPI_COMM nullptr initialization

doc/readthedocs/codingguidelines.rst
This PR cleans up the coding guideline section.
- Nicely format every guideline as its own paragraph.
- Add a little more info, reasoning, guidance
- Removed a few common knowledge items.
- Added new guideline on magic_enum, see #474
=> Update coding guidelines in docs

README.md, doc/readthedocs/developer_cluster.rst, doc/readthedocs/developmentguide.rst, doc/readthedocs/index.rst, doc/readthedocs/installation.rst, doc/readthedocs/tut_fluid_preexo.rst
Update the `README.md`. I was inspired by the README of [Queens](https://github.com/queens-py/queens).
I also removed the complete setup process of 4C from the README. It was too long, and it duplicates the information from our documentation.
I also moved the setup process to the top level and named it 'Installation'. Technically, it is not an installation of 4C. But I think everyone will understand that this is the page where you find information on how to set up 4C. 
Closes #279
=> Update the README

src/core/fem/src/general/utils/4C_fem_general_utils_integration.cpp, src/core/fem/src/general/utils/4C_fem_general_utils_integration.hpp
Add Gauss lobatto integration rules for hex cell types using fillquadrature routine (=tensor product of the 1D quadrature formulas).
@amgebauer
=> Add lobatto integration for hex cell type

apps/global_full/4C_global_full_main.cpp, src/core/io/src/4C_io_input_file.cpp
As of now, for the tool `4C --to-yaml` it is necessary to define the the dat file input AND the yaml output. Since I presume that one often might want to simply replace the .dat suffix by .yaml for the output filename, it shouldn't be necessary to define the output explicitly. 
This is what the PR mainly does. Overwriting an existing yaml file is prevented.
In addition, when the given input file (also for 4C simulations in general) does not exist, an error message will be thrown. As of now, if a yaml file name is given as input - and the respective file does not exist - the message was `Error message:   The input file '<whatever_your_inputfile_is>.yaml' must contain a map as root node`, which I don't find intuitive.
See discussion #490 .
=> Assume yaml filename for --to-yaml if not given

utilities/requirements.txt
I ran into a weird go error when first committing after upgrading to Ubuntu 24.04 (probably this one `https://github.com/pre-commit/pre-commit/pull/3130`). Updating pre-commit fixes this.
=> Update pre-commit to version 4.1.0

src/core/io/src/4C_io_input_spec_builders.cpp, src/core/io/src/4C_io_input_spec_builders.hpp, src/core/io/tests/4C_io_input_spec_test.cpp, utilities/create_json_schema.py, utilities/metadata_utils.py
Just as we don't like to use untyped strings, we also do not want to use them for the `selection`. This PR changes the new selection from #469 to work with enums.
FYI @bwirthl
=> Rework new selection to work with magic_enum

cmake/functions/four_c_testing_functions.cmake, src/contact/4C_contact_strategy_factory.cpp
the test command with omp threads used a semicolon to separate the different commands, e.g. test-command; unset OMP_VARIABLE. This led the test pass since the last command always evaluated to true.
Unfortunately, this hid a bug in the micro tests. #535 
Closes #535
=> Fix bug in cmake testing functions for omp threads

src/core/legacy_enum_definitions/4C_legacy_enum_definitions_conditions.cpp, src/ehl/4C_ehl_input.cpp
In the `Core::Conditions` class, a method `to_string` exists for `enum ConditionType`.
However, not all condition types have a corresponding string in the respective switch clause.
For now I am confident I added all missing ones. 
However, there is no guarantee that people don't add their new condition in the to_string method.
=> BugFix: Add missing ConditionType enum strings

.github/workflows/docker_prebuilt_4c.yml, docker/prebuilt_4C/Dockerfile, docker/prebuilt_4C_minimal/Dockerfile, docker/prebuilt_4C_minimal/README.md, presets/docker/CMakePresets.json
Provide a new docker image with only the 4C executable. Some unnecessary packages which are not required to run 4C, like paraview and clang, have been removed. The image with the full 4C build `ghcr.io/4c-multiphysics/4c:main` is 7.53GB. The new `4c-minimal:main` image is now at 2.73GB. Right now, I just remove things from the `4c-dependencies` image. This can be refactored in the future once we have a better way to manage our different docker images.
Additional info
- The PR also fixes an "error" for the prebuilt 4C image. As this image is tagged with main, it should also depend on the dependencies image `main`. This has not caused any harm yet because the dependencies `latest` and `main` tags point to the same image.
- The 4C `install` target only installs the 4C executable. So, …
=> 445 reduce size of docker image

src/contact/4C_contact_lagrange_strategy_wear.cpp, src/core/fem/tests/utils/4C_fem_general_element_dof_matrix_test.cpp, src/core/linalg/src/sparse/4C_linalg_blocksparsematrix.cpp, src/core/linalg/src/sparse/4C_linalg_multi_vector.hpp, src/core/linalg/src/sparse/4C_linalg_projected_precond.cpp, src/core/linalg/src/sparse/4C_linalg_vector.hpp, src/core/linalg/src/sparse/4C_linalg_view.hpp, src/core/linalg/tests/4C_linalg_vector_test.np2.cpp, src/core/linear_solver/src/amgnxn/4C_linear_solver_amgnxn_preconditioner.cpp, src/coupling/src/adapter/4C_coupling_adapter.cpp, src/ehl/4C_ehl_base.cpp, src/fsi/src/monolithic/nonlinear_solver/4C_fsi_nox_group.cpp, src/fsi/src/monolithic/nonlinear_solver/4C_fsi_nox_linearsystem.cpp, src/solver_nonlin_nox/4C_solver_nonlin_nox_group.cpp, src/solver_nonlin_nox/4C_solver_nonlin_nox_linearsystem.cpp, src/solver_nonlin_nox/4C_solver_nonlin_nox_singlestep_group.cpp, src/solver_nonlin_nox/4C_solver_nonlin_nox_solver_ptc.cpp, src/structure/4C_structure_timint_noxlinsys.cpp, src/structure_new/src/implicit/4C_structure_new_impl_generic.cpp, src/structure_new/src/model_evaluator/4C_structure_new_model_evaluator_contact.cpp, src/structure_new/src/nonlinear_solver/4C_structure_new_nln_linearsystem_scaling.cpp, src/structure_new/src/nonlinear_solver/4C_structure_new_timint_noxinterface.cpp, src/structure_new/src/utils/4C_structure_new_dbc.cpp
We frequently want to view Epetra datastructure as if they were our own wrapper. This class enables such a behavior with minimal modifications in the wrapper classes. We already had a basic version for vectors and I realized we can generalize it a little bit, to work for any combination of source type and wrapper type. 
Should help with some issues in #554
=> Create LinAlg::View for our wrappers

.github/workflows/docker_dealii.yml
I need to get this workflow onto main so I can manually trigger the build within https://github.com/4C-multiphysics/4C/pull/558.
Part of #506
=> Add dummy job to set up docker image with deal.II

src/fluid_ele/4C_fluid_ele_calc_poro.cpp, src/fluid_ele/4C_fluid_ele_calc_poro.hpp, src/fluid_ele/4C_fluid_ele_calc_poro_p1.cpp
I am investigating if we need `ElementType::pre_evaluate` in its current form. I suspect we don't . Anyway, this PR removes a similar function that is clearly useless.
=> Remove a do-nothing pre-evaluate

src/core/fem/src/condition/4C_fem_condition_definition.cpp, src/core/io/src/4C_io_input_file.cpp, src/core/io/src/4C_io_input_file.hpp, src/core/io/src/4C_io_input_parameter_container.hpp, src/core/io/tests/4C_io_input_file_test.cpp, src/global_data/4C_global_data_read.cpp
`InputFile::match_section` is the user-friendly interface to the input file. It gives you the data from the section in a `InputParameterContainter` with the same structure as the `InputSpec` you set up for that section. This PR uses this function for materials and conditions. Finally, the `in_section` function is moved into the internals.
Depends on #576 :heavy_check_mark:
=> Use InputFile::match_section

.github/workflows/nightly_tests.yml
I learned about this nice tool [ninjatracing](https://github.com/nico/ninjatracing) which allows to embed the detailed output from `-ftime-trace` within the project-wide info in .ninja_log. The results can be viewed as a flame graph like this (e.g. here: https://ui.perfetto.dev/):
This PR adds this information to the existing nightly job and provides the trace as an artifact.
Credit for the idea: https://www.youtube.com/watch?v=Oih3K-3eZ4Y
=> Enhance build time analysis with ninjatracing

.github/workflows/buildtest.yml
This PR adds the `4C_metadata.yaml` file to the artifacts. This is useful for FourCIPP since we can download the file for testing directly from the artifacts.
The JSON schema is already uploaded.
=> Upload metadata after build

cmake/configure/configure_MIRCO.cmake, src/contact_constitutivelaw/4C_contact_constitutivelaw_mirco_contactconstitutivelaw.cpp, src/contact_constitutivelaw/4C_contact_constitutivelaw_mirco_contactconstitutivelaw.hpp, unittests/contact_constitutivelaw/4C_mirco_pressure_contactconstitutivelaw_test.threads2.cpp
The shape factors for the pressure-based Green's function were earlier calculated using the MATLAB bem code and gave erroneous values for n=7 and n=8. Therefore, those are updated using Tamaas. Also, the git tag of MIRCO in 4C has been updated.
Calculation of composite Poisson's ratio has been removed as the composite Young's modulus (E*), calculated in MIRCO, already accounts for the Poisson's ratio, i.e., 1/E* = (1-nu^2)/E. See https://github.com/imcs-compsim/MIRCO/pull/100
The results of the MIRCO unittests have been updated for the pressure-based Green's function because of the updated influence coefficient matrix generation in MIRCO.
Closes #399
=> Update MIRCO shape factors and git tag

apps/global_full/CMakeLists.txt, cmake/configure/configure_ArborX.cmake, cmake/configure/configure_Backtrace.cmake, cmake/configure/configure_Boost.cmake, cmake/configure/configure_CLN.cmake, cmake/configure/configure_FFTW.cmake, cmake/configure/configure_HDF5.cmake, cmake/configure/configure_MIRCO.cmake, cmake/configure/configure_MPI.cmake, cmake/configure/configure_Qhull.cmake, cmake/configure/configure_Trilinos.cmake, cmake/configure/configure_magic_enum.cmake, cmake/configure/configure_ryml.cmake, cmake/functions/four_c_auto_define_module.cmake, cmake/functions/four_c_auto_define_tests.cmake, cmake/python/set_up_python.cmake, cmake/setup_install.cmake, cmake/setup_tests.cmake
I want to use 4C in another project, but configure failed since the scripts that configure our external dependencies were not found.
=> Replace CMAKE with PROJECT dirs

src/core/io/src/4C_io_input_parameter_container.hpp, src/core/io/src/4C_io_input_parameter_container.templates.hpp, src/core/io/tests/4C_io_input_parameter_container_test.cpp
- Enums were previously not recognized as StreamInsertable concepts due to namespace / lookup issues.
- This was fixed by moving the PrintHelper functions to the corresponding parameter container template file and including the corresponding enum utilities file.
- A dedicated unit test was added checking the stream-insertability.
Fixed by @sebproell and me.
Fixes the bug discussed in [588](https://github.com/4C-multiphysics/4C/pull/588#discussion_r2021107936)
=> Fix enum printing via magic_enum

.github/workflows/buildtest.yml, .github/workflows/nightly_tests.yml, cmake/functions/four_c_configure_dependency.cmake, presets/docker/CMakePresets.json
This new job turns off the dependencies that are optional. I only added a minimal test in PRs. I propose to test this in PRs, since it should not be slower than the rest of the pipeline. The question is how we should add this to nightly. Yes/no? With full tests?
Closes #509, Useful first step to test #506
=> CI: new job to compile with no optional dependencies

src/core/io/src/4C_io_input_file.cpp, src/core/io/src/4C_io_input_spec.cpp, src/core/io/src/4C_io_input_spec.hpp, src/core/io/src/4C_io_input_spec_builders.cpp, src/core/io/src/4C_io_input_spec_builders.hpp, src/core/io/tests/4C_io_input_spec_test.cpp
The first commit shuffles some code around (in the implementation). The second commit enhances various user-facing error messages when input does not match the specification.
=> InputSpec: refactor internals and add better errors

src/core/linalg/src/dense/4C_linalg_fixedsizematrix.hpp, src/core/linalg/src/dense/4C_linalg_tensor.hpp, src/core/linalg/src/dense/4C_linalg_tensor_meta_utils.hpp, src/core/linalg/tests/4C_linalg_tensor_operations_test.cpp, src/core/linalg/tests/4C_linalg_tensor_test.cpp
This is a first draft of a tensor class in 4C. Only few tensor operations are defined.
~~Currently, I'm using [Fastor](https://github.com/romeric/Fastor) as the backend for tensor operations.~~
I'm using the same internals as the `Core::LinAlg::Matrix`. This ensures that
(a) we use the same internal ordering of the values for tensors of rank 2
(b) we don't use different math kernels for basically the same thing.
This has of course the drawback that our own implementation is less flexible and also not really optimized for current hardware. But we might want to switch to a more powerful backend and then tensors and matrices profit the same.
Note, the Tensor as suggested here is just a different object but the mathematicals are identical. Tensor operations are more flexible, but also not …
=> Implement a Tensor class on-top of our fixed-size matrix routines

src/core/io/src/4C_io_input_file_utils.cpp
After doing some roundtrip tests (convert all .dat files from 4C to .yaml -> read in all 4C.yaml files with fourcipp -> dump all files again -> run all simulations with 4C) the following problem emerged
Similar to #581. One was able to enter anything into a design section, i.e.,
```
---------------------------------------------------------DLINE-NODE TOPOLOGY
NODE  1 4C_is_cool 1
---------------------------------------------------------DSURF-NODE TOPOLOGY
NODE  1 THIS_IS_THE_BEST_SIMULATION_ON_EARTH 1
```
This PR checks if the actual keyword in each line is identical to the current section (see first commit). The second commit fixes `DSURF` -> `DSURFACE` and the third commit fixes `DVOL` -> `DVOLUME`
@sebproell this could be improved in the future by not asserting this check but using the …
=> Fix d node topology

src/beaminteraction/src/4C_beaminteraction_conditions.cpp, src/beaminteraction/src/4C_beaminteraction_conditions.hpp, src/beaminteraction/src/4C_beaminteraction_contact_pair.cpp, src/beaminteraction/src/4C_beaminteraction_contact_pair.hpp, src/beaminteraction/src/4C_beaminteraction_submodel_evaluator_beamcontact.cpp
Up until now we could only create a single beam interaction pair for a single pairing of structural elements. This causes issues, if one wants to combine different coupling methods, e.g., line-to-surface and line-to-line contact interactions for beam-to-solid contact. This PR allows for multiple beam interaction conditions to create a beam contact pair for a single pairing of structural elements.
Note: A single beam interaction condition, e.g., beam-to-surface, beam-to-volume, ..., can still only create a single beam contact pair, as the underlying formulations don't not make sense otherwise.
=> Allow multiple beam contact pairs for element pair

apps/global_full/4C_global_full_main.cpp
The --to-yaml converter aborts when the output file already exists. To avoid the unnessary reading of the input file in this case, the reading of the file is now done after checking the output file. This will save some seconds.
This is useful for converting large files. The converter now aborts after 10 seconds instead of 30 seconds for a input file of 3 GB.
=> Check filename before reading file in --to-yaml

src/mat/4C_mat_structporo.cpp, src/mat/4C_mat_structporo.hpp
This PR add the `post_setup` call to the material `StructPoro`. This enables usage of materials that rely on this call (e.g. `mixture`) as the solid material within the poroelastic framework.
none
=> Add post setup call to StructPoro material

apps/global_full/4C_global_full_main.cpp
While starting with the conversion of `ssti` files I realized that using the `--to-yaml` option with only the current input file (.dat) was not working as the `replace_extension` call did also replace the file extension of the input file that is not yet available, thus reading of the dat file and subsequent conversion to 4C.yaml did not work.
=> Fix bug in --to-yaml

src/core/io/src/4C_io_input_spec_builders.cpp, src/core/io/src/4C_io_input_spec_builders.hpp, src/core/io/tests/4C_io_input_spec_test.cpp
I was trying to be too clever here and thought we don't need the check. 
Error looks like this now:
```
Could not match this input
DESIGN SURF DIRICH CONDITIONS:
- E: 1
NUMDOF: 3
ONOFF: [1,1,1]
VAL: [0,0,0]
FUNCT: [0,0,0,4]
against the given input specification. This was the best attempt to match the input:
[!] Candidate list 'DESIGN SURF DIRICH CONDITIONS'
[!] The following list entry did not match:
{
[ ] Matched parameter 'E'
[ ] Matched parameter 'NUMDOF'
[ ] Matched parameter 'ONOFF'
[ ] Matched parameter 'VAL'
[!] Candidate parameter 'FUNCT' (value has incorrect size)
[ ] Defaulted deprecated_selection 'TAG'
}
```
=> Validate size read from_parameter for yaml files

doc/documentation/installation.rst
Throw out things that are outdated or too specific. Mention a few (recent) improvements to the installation process.
Overall goal: try to write the docs in a way that they do not get outdated. Refer to external documentation if possible.
=> Clean up and improve docs on 4C installation

cmake/functions/four_c_auto_define_benchmark_tests.cmake, cmake/setup_tests.cmake, src/core/linalg/benchmark_tests/4C_linalg_tensor_benchmark.cpp, src/core/linalg/benchmark_tests/CMakeLists.txt, src/core/linalg/src/dense/4C_linalg_tensor.hpp, tests/benchmark_tests/4C_benchmark_tests_main.cpp
This provides infrastructure for micro-benchmarking tests. Useful for profiling or comparing different implementations. Setup is very similar to Google Test.
I added a few benchmark tests for the tensors added in #583.
Closes #611
=> Add Google Benchmark for micro-benchmark tests

src/core/binstrategy/4C_binstrategy_utils.cpp
I am trying to add the undefined behavior sanitizer (UBSAN) to our nightly sanitizer run. Locally, I run into a compiler warning for one loop. Rewriting it in a cleaner way removes the warning.
=> Rewrite a loop that triggers a compiler warning with UBSAN

src/mat/4C_mat_micromaterial.cpp, src/mat/4C_mat_micromaterial.hpp, src/mat/4C_mat_micromaterial_evaluate.cpp, src/mat/4C_mat_micromaterialgp_static.cpp, src/structure/4C_structure_dyn_nln_drt.cpp, tests/input_files/sohex8_multiscale_macro.dat
The density was not properly initialized in solid micro-macro simulations. In addition, for restart simulations also, no value was set, resulting in garbage values for the density, letting restart simulations fail.
This should be fixed now. I also tested it on an asan and a debug configuration on my workstation without failure.
Thanks also to @georghammerl and @sebproell for support during nasty debugging.
Closes #635
=> Fix bug in structure micro-micro

CITATION.cff
The correct SPDX identifier of our chosen license includes the "-or-later".
@4C-multiphysics/maintainer
=> Correct license identifier

src/core/linear_solver/src/method/4C_linear_solver_method_iterative.cpp, src/core/linear_solver/src/method/4C_linear_solver_method_linalg.cpp, src/inpar/4C_inpar_solver.cpp, tests/input_files/consinter3D_tsi_hex8_tet4.dat, tests/input_files/f2_channel_EOS_quad4_1000x10_quad_inflow_h_diam_to_opp.dat, tests/input_files/f2_channel_EOS_quad4_200x10_cubic_inflow.dat, tests/input_files/f2_drivencavity32x32_Re1000_stat.dat, tests/input_files/f3_beltrami_tet10_hdg.dat, tests/input_files/f3_cha_8x8x8_recongradl2.dat, tests/input_files/f3_cha_8x8x8_recongradspr.dat, tests/input_files/f3_decaying_hit_8x8x8.dat, tests/input_files/f3_decaying_hit_eb.dat, tests/input_files/f3_impl_channel_pressuregrad.dat, tests/input_files/f3_periodic_hill_w_forcing_24x12x12.dat, tests/input_files/f3_womersley.dat, tests/input_files/fsi_dc_mono_mtrss_ada_ab2_none.dat, tests/input_files/scatra_forced_hit_iso_8x8x8_dsm.dat, tests/input_files/sti_mono_2D_quad4_elch_s2i_butlervolmerpeltier_diabatic_AMG_vectorbased.dat, tests/input_files/volmortar3D_tsi_hex8_tet4.dat, tests/input_files/xfluid_stat_sliver_cut_instat.dat, tests/input_files/xfluid_taylor_couette_NavSlip_eps1.0_25x25_krylov_levelset_altgeogeneration.dat, tests/input_files/xfluid_taylor_couette_NavSlip_ri0.19_ro0.49_epsi1.0_epso1e-5_ti-2.5_to0.5_8x8_levelset_hex27.dat
Failed convergence of iterative linear solvers has lead to trouble in the past --- either in solver development or on applications, where "bad" Newton increments are likely to disturb/destroy the convergence of the outer Newton solver. This PR finally throws, if the iterative solver did not converge in the maximum number of iterations.
If necessary for the pipeline to pass or if desired by the community, I can add an input option to issue a warning instead. In order to be on the safe side, the new default behavior will be to throw.
UPDATE: I have added the option `THROW_IF_UNCONVERGED`, so that the user can overwrite default behavior and only gets a warning instead of an error.
=> Throw if iterative linear solver does not converge

.github/workflows/trilinos-develop.yml, dependencies/trilinos_develop/trilinos/install.sh, docker/trilinos_develop/Dockerfile, utilities/four_c_utils/src/four_c_utils/check_workflow_dependencies_hash.py
This PR adds a workflow that builds the 4C dependencies image with the Trilinos develop branch, builds 4C, and runs the tests. The workflow is scheduled to run on Saturdays at 8:00 am. 
~~Adds a workflow that builds the Docker image with the Trilinos develop version, builds 4C, and runs the tests.
This is a draft for now because~~
1. ~~the [build fails](https://github.com/ppraegla/4C/actions/runs/13005412107/job/36271309120) (something with arborX) and~~ fixed with #591 
2. ~~the workflow schedule is not finalized yet. Ideally, I would like to run this workflow weekly and allow the option to run the workflow manually for specific commit SHAs. However, I have not yet found a nice way to add the manual trigger without duplicating the jobs.~~ I think a manual run of the workflow with a …
=> Add workflow for testing against Trilinos develop

src/core/io/src/4C_io_meshreader.cpp, src/core/io/src/4C_io_meshreader.hpp
Split up a long function into reusable functions. This is useful so I can use all the nice rebalancing techniques for a discretization read from an exodus file. Refactoring powered by Copilot.
=> Split rebalancing into more useful parts

src/beaminteraction/src/4C_beaminteraction_submodel_evaluator_beamcontact.cpp, src/beaminteraction/src/4C_beaminteraction_submodel_evaluator_beamcontact.hpp, src/core/fem/src/geometric_search/4C_fem_geometric_search_access_traits.hpp, src/core/fem/src/geometric_search/4C_fem_geometric_search_bvh.cpp, src/core/fem/src/geometric_search/4C_fem_geometric_search_bvh.hpp, src/core/fem/src/geometric_search/4C_fem_geometric_search_distributed_tree.cpp, src/core/fem/src/geometric_search/4C_fem_geometric_search_distributed_tree.hpp, src/core/fem/src/geometric_search/4C_fem_geometric_search_utils.hpp, src/core/fem/tests/geometric_search/4C_fem_geometric_search_distributed_test.np3.cpp, src/core/fem/tests/geometric_search/4C_fem_geometric_search_test.cpp, src/core/rebalance/src/4C_rebalance_graph_based.cpp
This PR cleans up how we return results from the local and global collision search powered by ArborX. We how return a vector of `CollisionSearchResult` in the local search, that contains all the relevant information need (similar to how we already did it in the global search).
Furthermore, the internal way we perform the search and query the BVH was improved, so it should now be possible to simply split up the collision search functions into the creation of a BVH (which can be stored as a wrapped object) and a query part, enabling multiple different queries of a BVH.
@maxfirmbach @mayrmt
=> Improve ArborX interface

src/ssi/4C_ssi_base.cpp, src/ssi/4C_ssi_base.hpp, src/ssi/4C_ssi_coupling.cpp, src/ssi/4C_ssi_manifold_utils.cpp, src/ssi/4C_ssi_monolithic.cpp, src/ssi/4C_ssi_monolithic.hpp, src/ssi/4C_ssi_partitioned.cpp, src/ssi/4C_ssi_partitioned_1wc.cpp, src/ssi/4C_ssi_partitioned_2wc.cpp, src/ssi/4C_ssi_utils.cpp, src/ssi/4C_ssi_utils.hpp, src/ssti/4C_ssti_algorithm.cpp
I'll do some cleanup of the ssi module, where this is the first part to keep the PR reviewable. Some of the main things I did:
- remove unnecessary header inclusions
- improve readability of variable names
- remove unnecessary references to authors
- clang tidy suggestions:
- add const's
- add nodiscard's
- designated initalization
- remove redundant qualifiers to improve formatting and thereby readability
=> Some cleanup of the ssi module

src/core/fem/src/general/utils/4C_fem_general_utils_createdis.cpp, src/core/io/src/4C_io_meshreader.cpp, src/core/io/src/4C_io_meshreader.hpp, src/global_data/4C_global_data_read.cpp
This PR simplifies a massive function for global input of discretizations. As a side effect, this should enable the use of the three ways to read a discretization, from `ELEMENTS`, `DOMAIN` or `GEOMETRY` sections, for _all_ fields.
=> Unify input of discretizations

doc/documentation/doxygen.rst
This page was quite outdated. I am wondering whether we should remove most of the content here? The features of doxygen are listed elsewhere. Instead, we should probably explain a little more what constitutes good documentation.
Of course, the easiest way to get good documentation is to already have really good documentation so everybody mimics it in their new code (see e.g. deal.II).
=> Update documentation on doxygen

utilities/create_json_schema.py
With #376, the section `PROBLEM TYPE` has to be provided for input files to be valid. This is really nice, I hope the dependent requiredness of more sections will follow in the future :)
However, if you use the nice `INCLUDES` feature, your IDE/FourCIPP can't validate the partial file, since the required section might be in a different file. To avoid this problem, a second schema is created with your build (called `schema_partial.json`), which validates each section in the same way, but does not warn/fail validation in case required **sections** are not present. To make life easier, a new ending should be introduced: `4C.part.yaml`. Here is an example for my VSC setup for yaml valdiation:
```json
"yaml.schemas": {
"/home/rei/workspace/4C/build/schema.json": [
"*.4C.yaml"
], …
```
=> Add schema for partial 4C.yaml files

doc/documentation/src/developer_guide/codingguidelines.rst
I forgot to do this in #486. Also, addresses https://github.com/4C-multiphysics/4C/pull/486#discussion_r1984812270
=> Update docs on naming conventions

src/fsi/src/partitioned/model_evaluator/4C_fsi_str_model_evaluator_partitioned.cpp, src/structure_new/src/explicit/4C_structure_new_timint_explicit.cpp, src/structure_new/src/implicit/4C_structure_new_timint_implicit.cpp, src/structure_new/src/implicit/4C_structure_new_timint_implicit.hpp, src/structure_new/src/implicit/4C_structure_new_timint_implicitbase.hpp, src/structure_new/src/nonlinear_solver/4C_structure_new_nln_solver_generic.cpp, src/structure_new/src/nonlinear_solver/4C_structure_new_nln_solver_generic.hpp, src/structure_new/src/nonlinear_solver/4C_structure_new_nln_solver_nox.cpp, src/structure_new/src/nonlinear_solver/4C_structure_new_nln_solver_singlestep.cpp
Some accessor methods were diplicated, some were obsolete. There were also unnecessary copy-to-self calls in the `Solver::NOX` and `Solver::SingleStep`. I have cleaned all this up.
#359
=> Some refactoring of the group related methods in nonlinear solvers

doc/documentation/src/developer_guide/codingguidelines.rst, src/core/io/src/4C_io_input_parameter_container.hpp, src/core/io/src/4C_io_input_parameter_container.templates.hpp, src/core/io/src/4C_io_input_spec_builders.hpp, src/core/io/src/4C_io_value_parser.hpp, src/core/io/src/4C_io_yaml.hpp, src/core/linalg/src/dense/4C_linalg_utils_densematrix_funct.hpp, src/core/linalg/src/dense/4C_linalg_utils_tensor_interpolation.cpp, src/core/linalg/src/dense/4C_linalg_utils_tensor_interpolation.hpp, src/core/utils/src/stl_extension/4C_utils_enum.hpp, src/poroelast/4C_poroelast_monolithic.cpp, src/poroelast_scatra/4C_poroelast_scatra_monolithic.cpp, src/porofluid_pressure_based/4C_porofluid_pressure_based_timint_implicit.cpp, src/porofluid_pressure_based_elast/4C_porofluid_pressure_based_elast_monolithic.cpp, src/porofluid_pressure_based_elast_scatra/4C_porofluid_pressure_based_elast_scatra_monolithic_twoway.cpp, src/solid_3D_ele/4C_solid_3D_ele_factory.cpp, src/solid_scatra_3D_ele/4C_solid_scatra_3D_ele_factory.cpp, src/structure/4C_structure_timint.cpp, src/structure_new/src/4C_structure_new_timint_base.cpp, src/thermo/src/implicit/4C_thermo_timint_genalpha.cpp
This PR properly encapsulates the magic_enum dependency in a namespace `EnumTools`. Previously, I tried to make the enum IO operators available globally but this cannot work due to the lookup rules of C++.
FYI @dragos-ana
=> Put magic_enum reflection into EnumTools namespace

apps/pre_exodus/4C_pre_exodus_validate.cpp, apps/pre_exodus/4C_pre_exodus_writedat.cpp, src/core/io/src/4C_io_exodus.cpp, src/core/io/src/4C_io_exodus.hpp, src/core/io/src/4C_io_meshreader.cpp, src/global_data/4C_global_data_read.cpp
Closes #707
I further simplified the duplication we have in our Exodus code and removed the Shape enum.
=> Exodus: reorder indices for hex27

src/art_net/4C_art_net_explicitintegration.cpp, src/art_net/4C_art_net_explicitintegration.hpp
This pr enables the vtk-based output in the 1D artery elements
The old output mechanism was deleted. At least as far as I have seen, it has only output the owner so far. Maybe I miss something. To check the new output, the variables were temporarily added to the `4C_post_processor_single_field_writer.cpp`.
=> Add runtime output to 1d arteries

doc/documentation/CMakeLists.txt, doc/documentation/scripts/extract_cmake_variables.sh, doc/documentation/src/developer_guide/developer_cmake.rst, doc/documentation/src/installation/installation.rst
I've been meaning to do that for quite some time: add a list of all variables that CMake understands to the documentation. Looks like this:
The better configuration necessary for #664 will only make sense if people know which variables exist. The table is not perfect yet, as seen for the entries with `UNINITIALIZED` type. We can add a nicer entry for these in the next steps.
=> List all our CMake variables in the documentation

src/adapter/4C_adapter_str_structure_new.cpp, src/scatra_ele/4C_scatra_ele_calc_lsreinit.cpp, src/solver_nonlin_nox/4C_solver_nonlin_nox_group_prepostoperator.cpp, src/solver_nonlin_nox/4C_solver_nonlin_nox_linearsystem_prepostoperator.cpp, src/solver_nonlin_nox/4C_solver_nonlin_nox_linesearch_prepostoperator.cpp, src/structure_new/src/model_evaluator/4C_structure_new_model_evaluator_structure.cpp
We got the macro `INVALID_TEMPLATE_QUALIFIER` from Teuchos, but it expands to nothing. It probably expanded to `template` at some point. I scraped Trilinos' history because I was curious. This diff https://github.com/trilinos/Trilinos/commit/e84d37591efa83266c521a9e7cac4c38fb4a4985#diff-4512baff44d86eb6c683befac0f69efc98d906b6f47c762ec0e5a0a8af4e59c0R3-R12 suggests that there were once buggy compilers.
=> Remove INVALID_TEMPLATE_QUALIFIER

CMakeLists.txt, cmake/functions/four_c_auto_define_tests.cmake, cmake/functions/four_c_configure_dependency.cmake, cmake/functions/four_c_process_global_option.cmake, cmake/functions/four_c_testing_functions.cmake, cmake/setup_tests.cmake
Follows #724 
@ischeider @ppraegla I think this PR will fix #664 since the `mpiexec` args are now configurable. We might want to do this differently in the future -- should there even be a default? I hope it works for now.
@georghammerl I added the default values of CMake variables to the table introduced in #724.
=> CMake: ensure that cache variables are set

src/adapter/4C_adapter_scatra_fluid_coupling_algorithm.cpp, src/elch/4C_elch_dyn.cpp, src/elch/4C_elch_moving_boundary_algorithm.cpp, src/fs3i/4C_fs3i_fps3i_partitioned.cpp, src/fs3i/4C_fs3i_partitioned.cpp, src/fs3i/4C_fs3i_partitioned_2wc.cpp, src/levelset/4C_levelset_algorithm.hpp, src/levelset/4C_levelset_algorithm_utils.cpp, src/loma/4C_loma_algorithm.cpp, src/loma/4C_loma_dyn.cpp, src/mat/4C_mat_scatra_multiscale_gp.cpp, src/poroelast_scatra/4C_poroelast_scatra_base.cpp, src/porofluid_pressure_based_elast_scatra/4C_porofluid_pressure_based_elast_scatra_base.cpp, src/scatra/4C_scatra_algorithm.cpp, src/scatra/4C_scatra_cardiac_monodomain_dyn.cpp, src/scatra/4C_scatra_dyn.cpp, src/scatra/4C_scatra_timint_elch_scl.cpp, src/scatra/4C_scatra_timint_implicit.cpp, src/scatra/4C_scatra_timint_implicit.hpp, src/ssi/4C_ssi_base.cpp, src/ssi/4C_ssi_base.hpp, src/ssi/4C_ssi_coupling.cpp, src/ssi/4C_ssi_coupling.hpp, src/ssi/4C_ssi_monolithic.cpp, src/ssi/4C_ssi_partitioned_1wc.cpp, src/ssi/4C_ssi_partitioned_2wc.cpp, src/ssti/4C_ssti_algorithm.cpp, src/ssti/4C_ssti_algorithm.hpp, src/sti/4C_sti_algorithm.cpp, src/sti/4C_sti_dyn.cpp
Mainly, the set_velocity_field method was a complete mess where you needed to hand in nullptrs, etc., when you did not want to communicate the requested quantity.
This and similar methods that also call set state on the scalar transport discretization are refactored, such that they now consume a const reference to the data instead of a shared pointer. This way, only those smaller methods that are actually required are called, which used to be indicated with nullptrs.
=> Clean scatra set state methods

src/core/utils/src/result_test/4C_utils_result_test.cpp
Increase the width for the discretization name during result test output, as there have been discretization names, e.g., scatra_manifold, that have been too long. In this case, the discretization name and the quantity name were merged, making it harder to interpret.
=> Increase width for the discretization name during result test output

src/core/fem/src/discretization/4C_fem_discretization.hpp, src/core/fem/src/discretization/4C_fem_discretization_evaluate.cpp, src/core/fem/src/discretization/4C_fem_discretization_utils.hpp, src/core/fem/src/discretization/4C_fem_discretization_utils_dbc.cpp, src/core/fem/src/discretization/4C_fem_discretization_utils_evaluate.cpp
- The implicit time variable in conditions was unused (good -- it should not be done in this implicit way).
- We had a few `evaluate` helpers that were never used.
=> Remove some unused Condition and Discretization evaluation code

src/core/linalg/src/sparse/4C_linalg_multi_vector.hpp, src/core/linalg/src/sparse/4C_linalg_vector.hpp, src/core/linalg/src/sparse/4C_linalg_view.hpp, src/fsi/src/monolithic/nonlinear_solver/4C_fsi_nox_linearsystem.cpp, src/solver_nonlin_nox/4C_solver_nonlin_nox_linearsystem.cpp, src/structure/4C_structure_timint_noxlinsys.cpp
- Use `unique_ptr`
- Add an example to docs
- Remove the `shared_ptr` accessor. No need to propagate these further than necessary. We can use `shared_ptr_from_ref` instead.
=> Minor improvement to LinAlg::View

src/particle_engine/4C_particle_engine_particlereader.cpp
Follow up of cce0df77b512952df408dead231c82ecc95bc8af. Before this commit, the timing of reading a block of particles was printed. After the refactoring the printing was done after each read particle.
=> Remove unnecessary particle output

src/ale/4C_ale_utils_mapextractor.cpp, src/core/fem/src/condition/4C_fem_condition_selector.cpp, src/core/fem/src/condition/4C_fem_condition_selector.hpp, src/core/fem/src/condition/4C_fem_condition_utils.cpp, src/core/fem/src/condition/4C_fem_condition_utils.hpp, src/fluid/4C_fluid_utils_mapextractor.cpp, src/fpsi/4C_fpsi_coupling.cpp, src/fpsi/4C_fpsi_utils.cpp, src/fs3i/4C_fs3i_fps3i_partitioned.cpp, src/fs3i/4C_fs3i_partitioned.cpp, src/fsi_xfem/4C_fsi_xfem_coupling_comm_manager.cpp, src/porofluid_pressure_based_elast_scatra/4C_porofluid_pressure_based_elast_scatra_artery_coupling_nodebased.cpp, src/scatra/4C_scatra_timint_implicit.cpp, src/structure/4C_structure_aux.cpp
The `ConditionSelector` classes are heavily over-engineered OOP-style. This functionality can be condensed into a function.
=> Simplify ConditionSelector classes into a function

src/core/linalg/src/dense/4C_linalg_tensor.hpp, src/core/linalg/tests/4C_linalg_tensor_operations_test.cpp
This combination is missing in the current implementation.
=> Implement dot product between rank 1 tensors

presets/lnm/cluster/CMakePresets.json
This pull request disables the metadata generation in the LNM cluster presets. If enabled, the automated build of 4C on a cluster node in the [Queens](https://github.com/queens-py/queens) cluster test fails due to an MPI error (see https://github.com/queens-py/queens/pull/146#issuecomment-2848493756).  Of course it is also possible to add this build option as an additional variable in the queens pipeline setup (see https://github.com/queens-py/queens/pull/146#discussion_r2088429776), but we think it would make sense to disable the metadata generation on the clusters by default (this is also the default at the IMCS cluster).
Tagging @davidrudlstorfer @sbrandstaeter @knarfnitram
=> Disable metadata generation in lnm cluster presets

.github/ISSUE_TEMPLATE/release.md, doc/documentation/src/developer_guide/developer_release.rst, doc/documentation/src/developer_guide/developmentguide.rst, utilities/tag_images_for_release.sh
Currently draft, since the exact procedure might not be final.
We might want to automate step 6.
@4C-multiphysics/maintainer
=> Add administrative tasks for releasing 4C

src/mortar/4C_mortar_utils.cpp, src/mortar/4C_mortar_utils.hpp, src/ssi/4C_ssi_partitioned_1wc.cpp, src/timestepping/4C_timestepping_mstep.hpp
In #783, we realized that this function is confusing and causes issue when viewing data. In case you want to combine an existing Map and existing data, it seems more logical to create an object with the intended map and copy over the data from another object.
I'll see if I can replace more occurrences.
=> Remove calls to replace_map

src/structure_new/src/explicit/4C_structure_new_timint_explicit.cpp, src/structure_new/src/nonlinear_solver/4C_structure_new_nln_solver_singlestep.cpp
The final small preliminary refactoring prior to removing some solver classes. Unfortunately, the next PR will break backwards compatibility with the old versions of Trilinos, for this reason I decided to keep these small changes as a separate PR to have this intermediate state reflected in history.
#359, #379, #779
=> NOX move solution vector nullification to the explicit integrator

src/core/linalg/src/sparse/4C_linalg_map.cpp, src/core/linalg/src/sparse/4C_linalg_map.hpp, src/core/linalg/src/sparse/4C_linalg_multi_vector.hpp, src/core/linalg/src/sparse/4C_linalg_sparsematrixbase.hpp, src/core/linalg/src/sparse/4C_linalg_vector.hpp, src/core/linalg/src/sparse/4C_linalg_view.hpp, src/core/utils/src/stl_extension/4C_utils_owner_or_view.hpp
This PR enables the `LinAlg::View` class for _any type_, regardless of whether it has native view support. I'll point out how this works in the diff.
I apply it to `LinAlg::Map` here.
=> Enable LinAlg::View for Map

.pre-commit-config.yaml, utilities/code_checks/check_venv, utilities/code_checks/commit-msg, utilities/set_up_dev_env.sh
I propose to run our `commit-msg` hook via the pre-commit framework for easier upgrading and maintainability. Previously we made a hard copy, which is difficult to update on the user end.
=> Migrate commit-msg hook to pre-commit

src/ssi/4C_ssi_dyn.cpp, src/ssi/4C_ssi_monolithic.cpp, src/ssi/4C_ssi_monolithic.hpp, src/ssi/4C_ssi_monolithic_meshtying_strategy.cpp, src/ssi/4C_ssi_monolithic_meshtying_strategy.hpp
The SSI MeshtyingStrategy stored pointers to other objects within SSI, namely the SSIMaps and SSIMeshTying. This is now changed such that those objects are handed in to the respective method as a const reference whenever required
Further changes:
- added [[nodiscard]] where reasonable
- changed to std::unique_ptr as return type of the factory
=> Rework of ssi monolithic meshtying strategy

src/core/linalg/src/dense/4C_linalg_tensor.hpp, src/core/linalg/src/dense/4C_linalg_tensor_internals.hpp
Moves `CORE::LinAlg::Internal::Tensor` to `CORE::LinAlg::TensorInternal`
This is necessary since otherwise, the compiler does not find the free functions (`add`, `dot`, `ddot`, ...) in the operators (*, +, /, ...) when overloading them for different kind of tensors. They need to be in the same namespace.
Context: I'm currently working on a `SymmetricTensor`.
=> Move tensor internals into own file in same namespace

.github/workflows/buildtest.yml, .github/workflows/checkcode.yml, .github/workflows/coverage.yml, .github/workflows/docker.yml, .github/workflows/documentation.yml, .github/workflows/nightly_tests.yml, dependencies/oldest_supported/trilinos/install.sh, docker/oldest_supported/Dockerfile
This PR adds a docker image with the oldest supported dependencies. This image is updated in the same workflow as the existing image. We propose to run a nightly build on this image to catch wrong `#ifdefs` or APIs (see e.g. #806)  (unchached, so we don't overload the cache as much). Nightly should be enough since very few PRs change anything in the dependencies. We can always move it to PRs if the check fails too frequently.
Co-authored by @ppraegla 
Closes #483
=> Add image for oldest supported dependencies

src/adapter/4C_adapter_scatra_interface.hpp, src/adapter/4C_adapter_scatra_wrapper.hpp, src/fs3i/4C_fs3i.cpp, src/fs3i/4C_fs3i.hpp, src/levelset/4C_levelset_algorithm.cpp, src/levelset/4C_levelset_algorithm.hpp, src/levelset/4C_levelset_algorithm_reinit.cpp, src/scatra/4C_scatra_timint_elch.cpp, src/scatra/4C_scatra_timint_implicit.cpp, src/scatra/4C_scatra_timint_implicit.hpp, src/scatra/4C_scatra_timint_implicit_service.cpp, src/ssi/4C_ssi_base.cpp, src/ssi/4C_ssi_base.hpp, src/sti/4C_sti_algorithm.cpp, src/sti/4C_sti_monolithic.cpp, src/sti/4C_sti_monolithic.hpp, src/sti/4C_sti_partitioned.cpp
While starting to work on removing the call of the 4C-coded block preconditioning, I got annoyed by so many things in `scatra_timint_implicit`. Thus, I decided to do some cleanup first, which includes, e.g., removing init methods and moving the relevant work to the constructor, removing unused methods, fixing naming, etc.
=> Cleanup of scatra timint implicit

src/structure_new/src/explicit/4C_structure_new_timint_explicit.cpp, src/structure_new/src/implicit/4C_structure_new_timint_implicit.cpp, src/structure_new/src/nonlinear_solver/4C_structure_new_nln_solver_generic.cpp, src/structure_new/src/nonlinear_solver/4C_structure_new_nln_solver_generic.hpp, src/structure_new/src/nonlinear_solver/4C_structure_new_nln_solver_nox.cpp, src/structure_new/src/nonlinear_solver/4C_structure_new_nln_solver_nox.hpp
Some additional clean up after #798. Mainly, the removal of unnecessary `setup()` method and the internal flags. Now ctor does everything required for initialization.
#359, #379, #798
=> NOX: remove obsolete setup() method

.pre-commit-config.yaml, src/cut/4C_cut_kernel.hpp, src/poroelast/4C_poroelast_utils_setup.hpp, utilities/four_c_utils/pyproject.toml, utilities/four_c_utils/src/four_c_utils/check_includes_for_cycles.py, utilities/requirements.txt
This PR adds a nice modularity check based on an implementation in deal.II: https://github.com/dealii/dealii/pull/18013
The cycle in `cut` is only a thing if the `#ifdef` were turned on, but we want to remove these anyway (see #207).
=> Avoid include cycles

.github/workflows/nightly_tests.yml
Fixes failing nightly tests https://github.com/4C-multiphysics/4C/actions/runs/15220171403/job/42814245472. Follow up to #811
=> Fix missing job output in nightly action

src/core/comm/src/4C_comm_utils.cpp, src/core/linalg/src/sparse/4C_linalg_krylov_projector.cpp, src/fluid/4C_fluid_timint_genalpha.cpp, src/post/4C_post_ensight_writer.cpp
As the title indicates, this MR cleans up some unnecessary map instantiates and removes the corresponding comment. 
The copies can be removed since our map implementation should be able to handle the conversion. 
Follow up of #799  
Blocked by #817   
Final part of #552
=>  Remove unnecessary Map instantiations

src/beam3/4C_beam3_discretization_runtime_vtu_writer.cpp, src/beaminteraction/src/4C_beaminteraction_calc_utils.cpp, src/beaminteraction/src/4C_beaminteraction_submodel_evaluator_crosslinking.cpp, src/constraint_framework/4C_constraint_framework_embeddedmesh_solid_to_solid_mortar_manager.cpp, src/constraint_framework/4C_constraint_framework_embeddedmesh_solid_to_solid_utils.cpp, src/constraint_framework/4C_constraint_framework_embeddedmesh_solid_to_solid_utils.hpp, src/core/fem/src/condition/4C_fem_condition_utils.cpp, src/core/fem/src/condition/4C_fem_condition_utils.hpp, src/core/fem/src/dofset/4C_fem_dofset_merged_wrapper.cpp, src/core/rebalance/src/4C_rebalance_binning_based.cpp, src/coupling/src/adapter/4C_coupling_adapter.cpp, src/fluid/4C_fluid_implicit_integration.cpp, src/porofluid_pressure_based_elast_scatra/4C_porofluid_pressure_based_elast_scatra_artery_coupling_linebased.cpp, src/reduced_lung/4C_reduced_lung_main.cpp, src/scatra/4C_scatra_timint_meshtying_strategy_s2i.cpp, src/scatra/4C_scatra_utils.cpp, src/ssi/4C_ssi_utils.cpp, src/structure_new/src/nonlinear_solver/4C_structure_new_nln_linearsystem_scaling.cpp, src/xfem/4C_xfem_coupling_mesh.cpp, src/xfem/4C_xfem_coupling_mesh.hpp
I am trying to remove the `Condition*` from the `Node` object.  This PR improves a few utility functions to find nodes carrying conditions. I then use these functions to find these node IDs instead of asking the node object directly. There are still some places left where the old functions are used, but I would like to get this merged as a first step.
=> Remove more `get_condition` from Node class

unittests/mat/4C_electrode_test.cpp
Removes a hidden dat file. #598
=> Use yaml instead of dat in an electrode unit test

.github/workflows/coverage.yml
Our coverage report currently runs out of storage. This PR increases the number of test chunks from `60` to `90` to circumvent this problem.
https://github.com/4C-multiphysics/4C/actions/runs/15407249162
=> Increase number of test chunks for coverage report

.pre-commit-config.yaml
Without this change, most hooks run twice: once during `pre-commit` and once during `commit-msg` (since #797). Not the end of the world since they are super fast, but let's still correct this.
=> Avoid running pre-commit hooks multiple times

src/core/io/src/4C_io_input_spec_builders.hpp, src/core/io/src/4C_io_input_spec_validators.hpp, src/core/io/tests/4C_io_input_spec_test.cpp, src/core/io/tests/4C_io_input_spec_validators_test.cpp, src/scatra/4C_scatra_functions.cpp
This PR adds a `.validator` option to `InputSpecBuilders::parameter`. This allows to write something like
```cpp
parameter<double>("time_step_size", {..., .validator = positive<double>()});
```
or
```cpp
parameter<int>("my_special_id", {..., .validator = positive<int>() || in_set({-100, -200})});
```
or
```cpp
parameter<double>("mass_fraction", {..., .validator = in_range(excl(0.), 1.0)});
```
If validation fails, the failed check can print itself to help in debugging the input. The checks are deliberately basic (but I think quite powerful already). We can discuss more involved checks if they are truly useful. The goal here is to just do all the stupid checks one tends to forget about; like for positive parameters (I guess this is true for >90% of our doubles :laughing:)
I kind of came up …
=> Add validation of parsed values to InputSpecs

src/core/fem/src/general/utils/4C_fem_general_utils_fem_shapefunctions.hpp, src/core/utils/src/numerics/4C_utils_clnwrapper.cpp, src/core/utils/src/numerics/4C_utils_clnwrapper.hpp, src/cut/4C_cut_kernel.hpp, src/fluid_turbulence/4C_fluid_turbulence_statistics_cha.cpp, src/mat/4C_mat_plasticelasthyper.cpp, src/mat/4C_mat_plasticelasthyper.hpp, src/mat/elast/4C_mat_elast_aniso_structuraltensor_strategy.cpp, src/mat/elast/4C_mat_elast_aniso_structuraltensor_strategy.hpp
There are more #defines of constants left, but most of them are inside `_defines.hpp` files, which we should remove in the context of #207.
=> Remove various #defines of constants

src/core/linalg/src/dense/4C_linalg_utils_scalar_interpolation.cpp, src/core/linalg/src/dense/4C_linalg_utils_scalar_interpolation.hpp, src/core/linalg/tests/4C_linalg_utils_scalar_interpolation_test.cpp
This class provides functionality to interpolate scalar values at arbitrary locations. It supports different interpolation
types, including moving least squares (MLS), logarithmic interpolation, and log-domain MLS,
with customizable weighting functions and interpolation parameters.
This class is required for tensor interpolation methods , see Satheesh et al., 2024, 10.1002/nme.7373
=> Scalar interpolation class

src/core/linalg/benchmark_tests/4C_linalg_symmetric_tensor_benchmark.cpp, src/core/linalg/benchmark_tests/4C_linalg_tensor_benchmark.cpp, src/core/linalg/src/dense/4C_linalg_symmetric_tensor.hpp, src/core/linalg/src/dense/4C_linalg_tensor.hpp, src/core/linalg/src/dense/4C_linalg_tensor_internals.hpp, src/core/linalg/tests/4C_linalg_symmetric_tensor_operations_test.cpp, src/core/linalg/tests/4C_linalg_symmetric_tensor_test.cpp, unittests/common/unittest_utils/4C_unittest_utils_assertions_test.hpp
This PR introduces the implementation of symmetric tensors including benchmark tests and unit tests. The interface is the same as for normal `Tensor`s.
```cpp
SymmetricTensor<double, 3, 3> tensor{}; // tensor filled with zeros
//SymmetricTensor<double, 3, 4> tensor{}; // ill formed
Tensor<double, 3> t = {{1.0, 2.0, 3.0}};
SymmetricTensor<double, 3, 3> t_dyadic_t = self_dyadic(t); // internal memory storage like our stress-like Voigt notation (like PK2-stress)
SymmetricTensor<double, 3, 3, 3, 3> t_dyadic_t _dyadic_t _dyadic_t = self_dyadic<4>(t); // internal storage like our linearization of a stress-like Voigt vector w.r.t. a strain-like Voigt vector (like our cmat-matrix)
```
The internal data structure is compatible to the stress-like Voigt notation, so that we can create a …
=> Implement `SymmetricTensor`

cmake/functions/four_c_auto_define_benchmark_tests.cmake, tests/benchmark_tests/4C_benchmark_tests_main.cpp
Added the missing asan options to the executable of the address sanitizer.
=> Fix failing asan for benchmark tests

src/core/io/src/4C_io_input_spec_builders.cpp, src/core/io/src/4C_io_input_spec_builders.hpp, src/core/io/tests/4C_io_input_spec_test.cpp, utilities/metadata_utils.py
The internal InputSpecs create all_ofs to encode a full input object. Our additional tools can also profit from this information if we emit it as metadata.
=> Emit internal all_ofs to metadata

src/structure_new/src/4C_structure_new_factory.cpp, src/structure_new/src/4C_structure_new_timint_base.cpp, src/structure_new/src/4C_structure_new_timint_base.hpp, src/structure_new/src/4C_structure_new_timint_basedataglobalstate.hpp, src/structure_new/src/4C_structure_new_timint_basedatasdyn.hpp, src/structure_new/src/implicit/4C_structure_new_timint_implicit.cpp, src/structure_new/src/model_evaluator/4C_structure_new_model_evaluator_structure.cpp
Why dealing with NOX infrastructure, I encountered many members. I tried to remove non-const getters which are not in use, also I refactored the getters of basic type to return value instead of references.
#359
=> Remove non-const getter members from `BaseDataSDyn` and remove some obsolete

src/core/io/src/4C_io_input_spec_builders.cpp, src/core/io/src/4C_io_input_spec_builders.hpp, src/core/io/src/4C_io_input_spec_storage.hpp, src/core/io/tests/4C_io_input_input_field_test.cpp, src/core/io/tests/4C_io_input_spec_test.cpp, src/scatra/4C_scatra_functions.cpp, tests/input_files/scatra_2D_external_force_magnet.4C.yaml, utilities/create_json_schema.py, utilities/metadata_utils.py
Depends on #890 
Simplify the way a selection looks in the input file by kicking the selector value. Instead, we now require every possible choice to be named exactly like one of the enum constants you are selecting over (this is checked).
Old
```yaml
time_integration:
type: OST
OST:
theta: 0.66
```
New
```yaml
time_integration:
OST:
theta: 0.66
```
=> Simplify selection in input files

src/core/io/src/4C_io_input_field.hpp, src/core/io/src/4C_io_input_spec_builders.hpp, src/core/io/tests/4C_io_input_field_test.cpp, src/core/io/tests/4C_io_input_spec_test.cpp
The last missing piece to make the input_field() as powerful as all other parameters: allow to store it in struct members. Note that I need to make the InputField default constructible to allow a default-constructible struct with such a member. 
@maxiludwig I fixed a few small things along the way. Most importantly, the `input_field` should really take its own set of options and not use the ones from `parameter`. I just made `input_field` and `selection` parameters required for now as I am not sure what the best logic would be to make them optional.
This PR also fixes the duplicated access, i.e. no more `group("stiffness").get<>("stiffness");` but just `get<>("stiffness");`
@maxfirmbach Let's watch out for an git-invisible conflict with #893 since the access will change as indicated …
=> Allow to store input_field to structs

apps/global_full/CMakeLists.txt, utilities/create_json_schema.py
The file was accidentally named `4C_schema.json_partial.json` insted of `4C_schema_partial.json`.
=> Fix partial json schema name

src/core/linalg/src/dense/4C_linalg_tensor_svd.hpp, src/core/linalg/tests/4C_linalg_tensor_svd_test.cpp
A small routine computing the singular value decomposition of 2-tensors (using `Teuchos::LAPACK`)
=> Implement SVD for tensors

src/core/linalg/src/dense/4C_linalg_symmetric_tensor.hpp, src/core/linalg/src/dense/4C_linalg_tensor.hpp, src/core/linalg/src/dense/4C_linalg_tensor_internals.hpp, src/core/linalg/tests/4C_linalg_tensor_fad_test.cpp, src/core/utils/src/numerics/4C_utils_fad_meta.hpp
Achieving this was actually more involved than hoped.
During review, pay special attention to the new meta-utility header `src/core/utils/src/numerics/4C_utils_fad_meta.hpp`
Our tensors automatically deduce the result type of the operations. This is problematic for the Sacado-Fad types, which build upon lazy evaluation and need to be casted to their base-type. Obtaining the base-type was quite tricky, especially since I needed to avoid loading the heavy Sacado-header in the tensor-header.
A small caveat remains: We require that all scalar-types are the same if a FAD-type is detected. For some reason, automatic differentiation does not work otherwise. I ensured that other usages don't compile
```c++
Tensor<FAD, 2> fad_tensor = {{FAD(2, 0, 1.0), FAD(2, 1, 2.0)}};
// auto result = 2 * …
```
=> Allow FAD-types in tensors

src/core/linalg/src/dense/4C_linalg_tensor_fad.hpp, src/core/linalg/tests/4C_linalg_tensor_fad_test.cpp
This PR implements small utility functions for tensor derivatives. This makes it very easy to compute (and verify) derivatives of equations containing tensors. Non-symmetric tensors can be used in arbitrary ranks, e.g., computing the derivative of a rank-3 tensor w.r.t. a rank-4 tensor (resulting in a rank-7 tensor). Symmetric tensors can only be part of differentiation if they have rank 2 (probably the only really relevant cases) and not in combination with non-symmetric tensors.
Examples:
Tensor equation w.r.t. another tensor
```c++
const Tensor<double, 2> t = {{1.1, 1.2}};
const auto fad_t = make_auto_diff_tensor(t); // Creates a tensor with fad-value type
auto some_operation = 2.3*fad_t;
// obtain derivative w.r.t. fad_t -> Result is a Tensor<double, 2, 2>
const auto dt_dt = …
```
=> Implement utility functions for tensor derivative

src/core/io/benchmarks/4C_io_input_benchmark.cpp, src/core/io/benchmarks/CMakeLists.txt
Add two basic benchmarks for matching into a dynamic container or into structs. Analysing the benchmark already revealed a very costly copy that is removed with #911. The results with this change on my machine:
```
Benchmark                  Time             CPU   Iterations
------------------------------------------------------------
match_spec              3642 ns         3641 ns       192143
match_spec_struct       2600 ns         2600 ns       264764
```
=> Add benchmark for InputSpec::match

src/core/io/src/4C_io_input_spec.cpp, src/core/io/src/4C_io_input_spec_builders.cpp, src/core/io/tests/4C_io_input_file_test.cpp, src/core/io/tests/4C_io_input_spec_test.cpp
This simplifies internals and further incentivizes users to not use all_of/one_of as they cannot match them. All existing input already conforms to the new approach; I only had to adapt the tests.
Another motivation for this change is the fact that we made a copy of the spec before matching (to wrap it in an all_of) and this is quite expensive. It took half the time of a microbenchmark I made (will push this separately).
=> Disallow matching unnamed specs

src/core/io/src/4C_io_input_spec_builders.hpp
Update the doc of `input_field` which had a broken `@code` section.
@gilrrei This is the doc that is relevant for https://github.com/4C-multiphysics/4C/pull/907#issuecomment-2992258868. You would need to use an `input_field` spec for the parameters that you want to specify as element-wise fields.
=> Add missing @endcode tag in `input_field()` doc

src/core/linalg/src/dense/4C_linalg_utlis_quaternion_interpolation.cpp
Follows #876 
@abhi-satheesh Can you double check? It looks like the `assert` did not fire in the PR checks (but caused a problem locally).
@sebproell Do we define `NDEBUG` in the assertion mode in the PR checks?
=> Fix assertion in quaternion interpolation

.clang-tidy, src/art_net/4C_art_net_artery.hpp, src/contact/4C_contact_coupling2d.cpp, src/contact/4C_contact_coupling3d.cpp, src/contact/4C_contact_integrator.cpp, src/contact/4C_contact_interface_tools.cpp, src/contact/4C_contact_interpolator.cpp, src/contact/4C_contact_line_coupling.cpp, src/contact/4C_contact_node.cpp, src/contact/4C_contact_tsi_interface.cpp, src/contact/4C_contact_wear_interface.cpp, src/fluid_ele/4C_fluid_ele_calc_poro.cpp, src/mat/4C_mat_plasticgtn.cpp, src/mortar/4C_mortar_element_shapefct.cpp, src/mortar/4C_mortar_projector.cpp, src/xfem/4C_xfem_condition_manager.hpp
I tried to enable this check (https://clang.llvm.org/extra/clang-tidy/checks/bugprone/reserved-identifier.html) in deal.II once, and it was super expensive. Let's see how fast it would run here. I can at least fix whatever it finds.
=> Clang-tidy: enable check for reserved identifiers

doc/documentation/src/tools/tools.rst
Part of #598 
Update the tools page with basic information on related projects. I dropped the outdated dat-related projects. This page could provide links to learn about these tools. In the future, we should link to tutorials in these projects that specifically work with 4C
@dragos-ana @amgebauer @isteinbrecher @davidrudlstorfer @gilrrei @sbrandstaeter This is just a basic page. Feel free to edit sections with more info, appropriate tutorials, links, etc.
If I forgot any projects, please tell me here (or add them later). I did not leave anything out deliberately.
=> Docs: update tools page with info on related projects

src/core/comm/src/4C_comm_utils.cpp, src/core/linalg/src/sparse/4C_linalg_sparsematrix.hpp, src/coupling/src/adapter/4C_coupling_adapter.cpp, src/mortar/4C_mortar_matrix_transform.cpp, src/mortar/4C_mortar_utils.cpp, src/sti/4C_sti_monolithic.cpp
This PR follows the work on the wrapper classes for `Epetra_Export` and `Epetra_Import` removing some `get_epetra_export()` and `get_epetra_import()` calls from the physics modules. However there are still a few more calls that need to be removed, e.g. places where the code (either a Epetra_CrsMatrix or a FEVector) directly calls the import or export methods of `Epetra` .
#755
=> Remove some raw epetra export and import calls

src/core/comm/src/4C_comm_exporter.cpp, src/core/comm/src/4C_comm_exporter.hpp, src/stru_multi/4C_stru_multi_microstatic.cpp
Use our concepts for types that can be communicated via MPI instead of specializations for a few select cases.
=> Generalize data types supported in Exporter

tests/input_files/fsi_fp_mono_ss_ga_ga.4C.yaml
As suspected, this test is susceptible for little different evaluation of the st-venant-kirchhoff material. The new way to evaluate the St. Venant-Kirchhoff material is $\boldsymbol{S}=\lambda \mathrm{tr} (\boldsymbol{E}) \boldsymbol{I} + 2 \mu \boldsymbol{E}$, the old way was $\boldsymbol{S} = \boldsymbol{C} : \boldsymbol{E}$.
Changing it back to $\boldsymbol{S} = \boldsymbol{C} : \boldsymbol{E}$ fixes the failing test on my workstation.
This PR adapts the tolerance slightly (unifies `lambday` with `lambdax` and `lambdaz`). The tolerance for `lambdax` and `lambdaz` have been adapted in #662.
Closes #951
=> Adjust tolerance of gaga-FSI test

src/core/fem/src/condition/4C_fem_condition.cpp, src/core/fem/src/condition/4C_fem_condition.hpp, src/core/fem/src/condition/4C_fem_condition_definition.cpp, src/core/fem/src/condition/4C_fem_condition_definition.hpp, src/core/fem/src/discretization/4C_fem_discretization_conditions.cpp, src/global_data/4C_global_data_read.cpp, src/global_legacy_module/4C_global_legacy_module_validconditions.cpp, src/global_legacy_module/4C_global_legacy_module_validconditions.hpp
- Compute correct IDs for manual node set specification early.
- Update a few docs.
- Remove unused helpers.
=> Clean up unused and complicated code for condition

src/core/io/src/4C_io_yaml.cpp, src/core/io/tests/4C_io_input_spec_test.cpp
Found while thinking about #954, although it is a different problem (and this one is clearly a bug!).
=> YAML: quoted values can only be strings

utilities/four_c_utils/src/four_c_utils/check_includes.py
This fix is needed to also detect [these file types](https://4c-multiphysics.github.io/4C/documentation/developer_guide/codingguidelines.html#types-of-source-files-used-within-fourc).
=> Fix include style pre-commit hook

src/core/io/src/4C_io_input_spec_builders.cpp, src/core/io/src/4C_io_input_spec_builders.hpp, src/core/io/src/4C_io_input_spec_storage.hpp, src/core/io/tests/4C_io_input_spec_test.cpp, src/core/utils/src/functions/4C_utils_symbolic_expression.hpp
After the rework in #913 #916 #919, this PR provides simpler input for a SymbolicExpression.
```
auto spec = InputSpecBuilders::symbolic_expression<double, "x", "y">("expr");
``` 
will match an input like
```yaml
expr: "x + y"
```
The string is immediately parsed into an expression. If this fails, it will be reported as an input error.
FYI @bgoderbauer @maxiludwig @engstlerL
=> InputSpec for SymbolicExpression

src/core/io/src/4C_io_exodus.cpp, src/core/io/src/4C_io_exodus.hpp
We previously ignored some errors and warnings that EXODUS could generate.
=> Exodus reader always checks for errors

src/core/fem/src/discretization/4C_fem_discretization_evaluate.cpp, src/core/fem/src/discretization/4C_fem_discretization_faces.cpp, src/core/fem/src/discretization/4C_fem_discretization_hdg.cpp, src/core/fem/src/discretization/4C_fem_discretization_hdg.hpp, src/core/fem/src/discretization/4C_fem_discretization_utils.cpp, src/core/fem/src/discretization/4C_fem_discretization_utils.hpp, src/core/fem/src/discretization/4C_fem_discretization_utils_dbc.cpp, src/core/fem/src/discretization/4C_fem_discretization_utils_evaluate.cpp, src/core/fem/src/nurbs_discretization/4C_fem_nurbs_discretization.cpp, src/core/fem/src/nurbs_discretization/4C_fem_nurbs_discretization.hpp, src/fluid/4C_fluid_DbcHDG.cpp, src/fluid/4C_fluid_DbcHDG.hpp, src/fluid/4C_fluid_implicit_integration.cpp, src/structure/4C_structure_timint.cpp, src/structure_new/src/4C_structure_new_timint_basedataglobalstate.cpp, src/structure_new/src/model_evaluator/4C_structure_new_model_evaluator_structure.cpp
Found this while working on #935 where this clashes with `Core::Utils`. I don't think the nested `FE::Utils` namespace is useful, so I removed it to follow the general recommendation that if in doubt, fewer namespaces are better.
Part of #51 
I recommend ignoring whitespace changes for the review.
=> Remove FE::Utils namespace

.github/actions/build_4C/action.yml
I don't really understand why the ccache action per default appends the timestamp to the cache key. The result is that we have a lot of redundant caches for single branches and might lose the (important) caches from the main branch. Without the timestap, new cache entries replaces old ones from the same branch.
@davidrudlstorfer
=> Don't append timestamp to ccache key

src/core/linalg/src/dense/4C_linalg_symmetric_tensor.hpp, src/core/linalg/src/dense/4C_linalg_tensor.hpp, src/core/linalg/src/dense/4C_linalg_tensor_internals.hpp
GCC is not able to optimize the old code, so we make it explicit
=> Performance improvements for rank 4 tensors (GCC)

README.md, doc/documentation/src/tools/tools.rst
I added a link to our related projects/tools to the README to point new users to these tools. I was prepared to create the list as well. But saw that the list already existed. I didn't know we already had it in the repo.
I also added [pipapo](https://github.com/particles-pipapo/pipapo) to the list. @gilrrei
=> Add link to related projects to README

src/contact_constitutivelaw/4C_contact_constitutivelaw_brokenrational_contactconstitutivelaw.hpp, src/contact_constitutivelaw/4C_contact_constitutivelaw_contactconstitutivelaw.hpp, src/contact_constitutivelaw/4C_contact_constitutivelaw_cubic_contactconstitutivelaw.hpp, src/contact_constitutivelaw/4C_contact_constitutivelaw_linear_contactconstitutivelaw.hpp, src/contact_constitutivelaw/4C_contact_constitutivelaw_mirco_contactconstitutivelaw.hpp, src/contact_constitutivelaw/4C_contact_constitutivelaw_power_contactconstitutivelaw.hpp
- Remove unused method from inheritance structure
- Fix groups in doxygen
Follows #1037
=> Rough surface contact: remove unused method, fix doxygen

tests/input_files/fsi_dc_mono_fs_ga_ga.4C.yaml, tests/input_files/fsi_pw_mono_ss_ost_ga_muelu.4C.yaml, tests/input_files/xml/multigrid/fluid_solid_ale.xml
By accident, we did define the minimum size of an aggregate twice in the aggregation sublist of MueLu. This PR fixes that.
=> Remove duplicate parameter definition

src/contact_constitutivelaw/4C_contact_constitutivelaw_brokenrational_contactconstitutivelaw.cpp, src/contact_constitutivelaw/4C_contact_constitutivelaw_brokenrational_contactconstitutivelaw.hpp, src/contact_constitutivelaw/4C_contact_constitutivelaw_bundle.cpp, src/contact_constitutivelaw/4C_contact_constitutivelaw_bundle.hpp, src/contact_constitutivelaw/4C_contact_constitutivelaw_contactconstitutivelaw.hpp, src/contact_constitutivelaw/4C_contact_constitutivelaw_contactconstitutivelaw_parameter.hpp, src/contact_constitutivelaw/4C_contact_constitutivelaw_cubic_contactconstitutivelaw.cpp, src/contact_constitutivelaw/4C_contact_constitutivelaw_cubic_contactconstitutivelaw.hpp, src/contact_constitutivelaw/4C_contact_constitutivelaw_interface.cpp, src/contact_constitutivelaw/4C_contact_constitutivelaw_linear_contactconstitutivelaw.cpp, src/contact_constitutivelaw/4C_contact_constitutivelaw_linear_contactconstitutivelaw.hpp, src/contact_constitutivelaw/4C_contact_constitutivelaw_mirco_contactconstitutivelaw.cpp, src/contact_constitutivelaw/4C_contact_constitutivelaw_mirco_contactconstitutivelaw.hpp, src/contact_constitutivelaw/4C_contact_constitutivelaw_power_contactconstitutivelaw.cpp, src/contact_constitutivelaw/4C_contact_constitutivelaw_power_contactconstitutivelaw.hpp, unittests/contact_constitutivelaw/4C_brokenrational_contactconstitutivelaw_test.threads2.cpp, unittests/contact_constitutivelaw/4C_cubic_contactconstitutivelaw_test.threads2.cpp, unittests/contact_constitutivelaw/4C_linear_contactconstitutivelaw_test.threads2.cpp, unittests/contact_constitutivelaw/4C_mirco_force_contactconstitutivelaw_test.threads2.cpp, unittests/contact_constitutivelaw/4C_mirco_pressure_contactconstitutivelaw_test.threads2.cpp, unittests/contact_constitutivelaw/4C_power_contactconstitutivelaw_test.threads2.cpp
- Pass gap values as `const`
- Remove unused header inclusions
- Avoid abbreviation in method name
=> Refactor contact constitutive law implementations

src/config/4C_config.hpp.in, src/config/4C_config_revision.hpp.in
I came across two files in our repository, there were missing the SPDX license identifier. This PR adds the missing content.
=> Add missing license identifier to files

cmake/setup_global_options.cmake, src/constraint/4C_constraint_penalty.cpp, src/constraint/4C_constraint_penalty.hpp, src/fluid_ele/4C_fluid_ele_calc_xfem.cpp, src/fluid_ele/4C_fluid_ele_calc_xfem.hpp, src/fluid_ele/4C_fluid_ele_evaluate.cpp, src/fluid_ele/4C_fluid_ele_evaluate_utils.hpp, src/poroelast/4C_poroelast_monolithic.cpp, src/solid_poro_3D_ele/4C_solid_poro_3D_ele_calc_lib.hpp
Based on a discussion with @marksidoro, I think we should turn on standard library assertions. They already uncovered some UB, e.g. #1017. Note that starting from GCC 15, these assertions are turned on by [default for unoptimized builds](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=112808), so we should start to fix these issues. Of course, we first need to fix all failures before this PR can be merged. Let's see what the fallout is going to be.
All issues are now fixed.
=> Enable _GLIBCXX_ASSERTIONS in assert mode

src/contact/4C_contact_paramsinterface.hpp, src/solver_nonlin_nox/4C_solver_nonlin_nox_group.cpp, src/solver_nonlin_nox/4C_solver_nonlin_nox_group.hpp, src/structure_new/src/implicit/4C_structure_new_impl_generic.cpp, src/structure_new/src/model_evaluator/4C_structure_new_model_evaluator_data.cpp, src/structure_new/src/model_evaluator/4C_structure_new_model_evaluator_data.hpp
Remove the unused parts of `Nln::Group` and also some other dependent classes that use its interface.
#359
=> Remove obsolete correction and eigenvalues objects `NOX::Nln::Group`

src/constraint/4C_constraint_lagpenconstraint_noxinterface.cpp, src/contact/4C_contact_meshtying_noxinterface.cpp, src/contact/4C_contact_noxinterface.cpp, src/fs3i/4C_fs3i_biofilm_fsi.cpp, src/solver_nonlin_nox/4C_solver_nonlin_nox_aux.cpp, src/solver_nonlin_nox/4C_solver_nonlin_nox_aux.hpp, src/structure_new/src/nonlinear_solver/4C_structure_new_timint_noxinterface.cpp, src/structure_new/src/nonlinear_solver/4C_structure_new_timint_noxinterface.hpp
I have removed some obsolete creation of NOX vector views when computing the norms since our `LinAlg::Vector` can compute them itself. I also removed some other unnecessary calls to `get_ref_of_epetra_vector()`.
#359
=> Generalize norms evaluation for NOX vectors and reduce the use of `get_ref_of_epetra_vector()`

src/core/io/src/4C_io_yaml.hpp
As discussed during the workshop, this might speed things up when parsing very large containers.
@maxfirmbach Could you give this a try on the large example?
=> Reserve container space when parsing YAML

src/structure_new/src/linear_solver/4C_structure_new_solver_factory.cpp, src/structure_new/src/linear_solver/4C_structure_new_solver_factory.hpp
The implementation did not work in the debug mode if more than one dofset has been defined on the structure discretization. This is changed now by explicitly accessing the dofset 0, which is the intended behavior in these cases.
=> Fix error in linear solver factory for new structure

unittests/mat/4C_druckerprager_test.cpp
The unit test for a solid material does not need to know about beams, so it should not include beam headers.
=> Remove unused header inclusions

src/core/linalg/src/dense/4C_linalg_tensor_matrix_conversion.hpp, src/core/linalg/tests/4C_linalg_tensor_matrix_conversion_test.cpp, src/solid_3D_ele/4C_solid_3D_ele_calc_displacement_based.hpp, src/solid_3D_ele/4C_solid_3D_ele_calc_eas.hpp, src/solid_3D_ele/4C_solid_3D_ele_calc_fbar.hpp, src/solid_3D_ele/4C_solid_3D_ele_calc_lib.hpp, src/solid_3D_ele/4C_solid_3D_ele_calc_lib_fbar.hpp, src/solid_3D_ele/4C_solid_3D_ele_calc_mulf.hpp, src/solid_3D_ele/4C_solid_3D_ele_calc_mulf_fbar.hpp, src/solid_poro_3D_ele/4C_solid_poro_3D_ele_calc_lib.hpp, src/solid_poro_3D_ele/4C_solid_poro_3D_ele_calc_pressure_based.cpp, src/solid_poro_3D_ele/4C_solid_poro_3D_ele_calc_pressure_velocity_based.cpp
It is more convinient to use a `std::array<Tensor<double, 3>, num_nodes>` to represent the material derivatives of the shape functions. This PR also provides a function that creates a Matrix-view of the corresponding data.
I will use this in #961
=> Use array of Tensors for material derivative of shape functions

src/core/io/src/4C_io_exodus.cpp, src/core/io/src/4C_io_exodus.hpp, src/core/io/src/4C_io_input_spec_builders.hpp, src/core/io/tests/4C_io_input_spec_test.cpp, src/global_legacy_module/4C_global_legacy_module_validparameters.cpp, utilities/create_json_schema.py, utilities/metadata_utils.py
Requested by and implemented together with @ischeider 
FYI @c-p-schmidt, you also requested this feature a while ago
=> Allow documentation of enum values in input

doc/documentation/src/community/community_roles.rst
As we have recently decided in our internal code workshop, the monthly meeting will now be called "community meeting" to even better indicate the target audience: the 4C community.
This also moves the info on the community meeting out of the "developer" section, since the community meeting is not restricted to developers, but addresses the entire 4C community.
=> Rename the "developer meeting" to "community meeting"

src/contact/4C_contact_nox_nln_contact_linearsystem.cpp, src/contact/4C_contact_nox_nln_contact_linearsystem.hpp, src/fsi/src/monolithic/nonlinear_solver/4C_fsi_nox_linearsystem_gcr.cpp, src/fsi/src/monolithic/nonlinear_solver/4C_fsi_nox_linearsystem_gcr.hpp, src/solver_nonlin_nox/4C_solver_nonlin_nox_forward_decl.hpp, src/solver_nonlin_nox/4C_solver_nonlin_nox_linearproblem.hpp, src/solver_nonlin_nox/4C_solver_nonlin_nox_linearsystem.cpp, src/solver_nonlin_nox/4C_solver_nonlin_nox_linearsystem.hpp, src/solver_nonlin_nox/4C_solver_nonlin_nox_scaling.hpp, src/structure/4C_structure_timint_noxlinsys.cpp, src/structure_new/src/nonlinear_solver/4C_structure_new_nln_linearsystem_scaling.cpp, src/structure_new/src/nonlinear_solver/4C_structure_new_nln_linearsystem_scaling.hpp
The next step to proceed with #1071 is to get rid of `Epetra_LinearProblem`. It is now only used in `NOX::FSI::LinearSystemGCR` (see comment below) an in `Core::LinearSolver::DirectSolver` for older version of Trilinos.
I had also to bring back the use of `NOX::Epetra::Scaling` in `NOX::FSI::LinearSystemGCR` since this system implements its own GCR and GMRES solution algorithms, this was earlier removed in #1077. Surely, these manual algos should be replaced by the suitable Trilinos packages. So since this class requires significant refactoring anyway, I think it is OK to have both `NOX::Epetra::Scaling` and `Epetra_LinearProblem` still used there. Alternative solutions would be to either disable the scaling feature (in fact, it is not used currently) or to create a `SparseOperator`-like …
=> Replace `Epetra_LinearProblem` with a custom class

src/core/linalg/src/sparse/4C_linalg_sparsematrix.cpp, src/core/linalg/src/sparse/4C_linalg_sparsematrix.hpp, src/core/rebalance/src/4C_rebalance_graph_based.cpp
Reduce the use and mentions of Epetra in `Core::LinAlg::SparseMatrix`.
Part of #863
=> Reduce Epetra in Core::LinAlg::SparseMatrix

src/core/fem/src/general/utils/4C_fem_general_utils_superconvergent_patch_recovery.cpp, src/core/io/src/4C_io_discretization_visualization_writer_mesh.cpp, src/core/linalg/src/sparse/4C_linalg_fevector.cpp, src/core/linalg/src/sparse/4C_linalg_fevector.hpp, src/core/linalg/src/sparse/4C_linalg_graph.cpp, src/core/linalg/src/sparse/4C_linalg_graph.hpp, src/porofluid_pressure_based_elast_scatra/4C_porofluid_pressure_based_elast_scatra_artery_coupling_linebased.cpp, src/porofluid_pressure_based_elast_scatra/4C_porofluid_pressure_based_elast_scatra_artery_coupling_nonconforming.cpp, src/thermo/src/implicit/4C_thermo_timint_impl.cpp
As the title indicates this MR substitutes the `Epetra_BlockMap` with the Map interface for the FEVector interface and the graph interface.
=> Remove Epetra_BlockMap from constructors

src/core/io/src/4C_io_input_file.cpp, src/core/io/src/4C_io_input_spec.cpp, src/core/io/src/4C_io_input_spec.hpp, src/core/io/src/4C_io_input_spec_builders.cpp
So far, `InputSpec` has always made a copy. `InputSpec` has only const methods and cannot mutate its state after construction (at least the user-facing part cannot). Thus, we can internally share repeated parts of an InputSpec. This PR serves as preparation for a new feature that also exports the info about shared specs to the metadata and schema.
Note that no change in the user code is required. This PR demonstrates how `shared_ptr` is meant to be used (IMHO): as an implementation detail of classes, hidden from clients.
=> Give InputSpec shallow copy behavior

src/beaminteraction/CMakeLists.txt, src/beaminteraction/src/CMakeLists.txt, src/coupling/CMakeLists.txt, src/coupling/src/adapter/CMakeLists.txt, src/fsi/CMakeLists.txt, src/fsi/src/CMakeLists.txt, src/lubrication/CMakeLists.txt, src/lubrication/src/CMakeLists.txt, src/mixture/CMakeLists.txt, src/mixture/src/CMakeLists.txt, src/shell_kl_nurbs/CMakeLists.txt, src/shell_kl_nurbs/src/CMakeLists.txt, src/structure_new/CMakeLists.txt, src/structure_new/src/CMakeLists.txt, src/structure_new/src/explicit/CMakeLists.txt, src/structure_new/src/implicit/CMakeLists.txt, src/structure_new/src/linear_solver/CMakeLists.txt, src/structure_new/src/model_evaluator/CMakeLists.txt, src/structure_new/src/nonlinear_solver/CMakeLists.txt, src/structure_new/src/output/CMakeLists.txt, src/structure_new/src/predict/CMakeLists.txt, src/structure_new/src/utils/CMakeLists.txt, src/thermo/CMakeLists.txt, src/thermo/src/CMakeLists.txt
As discussed in #1096, this PR moves internal dependencies higher up. The old way also worked, but the new way is more intuitive.
=> Cmake: move internal dependencies to module root

src/core/io/src/4C_io_input_spec_validators.cpp, src/core/io/src/4C_io_input_spec_validators.hpp, src/core/io/tests/4C_io_input_spec_validators_test.cpp, src/inpar/4C_inpar_scatra.cpp, utilities/create_json_schema.py, utilities/metadata_utils.py
Allows specifying a regex pattern for strings. I don't anticipate a lot of uses for this case, but it is exactly what we need for validating the version number within #74. It is trivial to add the pattern in a general way, so I went for this option rather than special hackery for certain fields.
=> Add pattern validator for input strings

cmake/functions/four_c_process_global_option.cmake, cmake/setup_global_options.cmake
Part of #1073
I decided to remove the `FOUR_C_CXX_DEBUG_FLAGS` etc. since they aren't useful if we don't do multi-configuration builds. Technically, a breaking change, but I doubt that anybody uses these.
=> CMake: document FOUR_C_CXX_ variables

src/core/fem/src/nurbs_discretization/4C_fem_nurbs_discretization_knotvector.cpp, src/core/fem/src/nurbs_discretization/4C_fem_nurbs_discretization_knotvector.hpp, src/core/io/src/4C_io_input_file_utils.cpp, src/core/io/src/4C_io_input_file_utils.hpp, src/global_data/4C_global_data_read.cpp, unittests/geometry_pair/4C_geometry_pair_line_to_volume_segmentation_geometry_functions_test.hpp
The `KNOTVECTORS` sections are legacy sections that should become nested YAML. While looking through the code to see how this can be achieved, I performed a little cleanup.
=> Minor cleanup in Knotvectors

src/beaminteraction/src/4C_beaminteraction_str_model_evaluator.cpp
#1086 introduces a nice check for the compatibility of beam-to-beam point couplings and beam-to-beam contact pairs. This check is extended in such a way, that we don't allow point couplings between two beams that are potentially in contact with each other. Point couplings between two beams that are possibly in contact with other beams are OK.
=> Improve beaminteraction checks

src/core/utils/src/functions/4C_utils_symbolic_expression.cpp, src/core/utils/src/functions/4C_utils_symbolic_expression.hpp, src/core/utils/src/functions/4C_utils_symbolic_expression_details.hpp, src/core/utils/tests/functions/4C_utils_symbolic_expression_test.cpp
In order to implement https://github.com/4C-multiphysics/4C/issues/571#issuecomment-3214966458 but also as a general extension, this PR adds comparison operators (`>`, `>-=`, `<`, `<=`, `==`, `!=`) and logical operators (`!`, `&&` and `||`) to the SymbolicExpression.
I think this basically makes the `heaviside` function that was implemented before obsolete, because theses conditions are more powerful and readable. Compare e.g.
```
f(x) = 2*H(3 - x) + (2 + (x - 3))*(H(x - 3) - H(x - 7)) + 6*H(x - 7)
```
vs.
```
f(x) = (x < 3)*2 + ((x >= 3) && (x < 7))*(2 + (x - 3)) + (x >= 7)*6
```
=> Add logical operators to symbolic expressions

src/core/io/src/4C_io_input_spec_builders.hpp, src/core/io/src/4C_io_input_types.hpp, src/core/io/src/4C_io_value_parser.hpp, src/core/io/src/4C_io_yaml.hpp, src/core/io/tests/4C_io_input_spec_test.cpp, utilities/create_json_schema.py, utilities/metadata_utils.py
Extend InputSpecs to support std::pair as a supported type. This includes extending the schema generation functionalities and YAML read/write toolings to support std::pair. The first commit adds a compile-time check in SizeChecker to catch missing template implementations for types where rank != 0. 
Preparation for #1139
=> Support std::pair as an InputSpec type

src/fsi/src/monolithic/nonlinear_solver/4C_fsi_nox_linearsystem.cpp, src/fsi/src/monolithic/nonlinear_solver/4C_fsi_nox_linearsystem.hpp, src/fsi/src/monolithic/nonlinear_solver/4C_fsi_nox_linearsystem_gcr.cpp, src/fsi/src/monolithic/nonlinear_solver/4C_fsi_nox_linearsystem_gcr.hpp, src/solver_nonlin_nox/4C_solver_nonlin_nox_linearsystem.cpp, src/solver_nonlin_nox/4C_solver_nonlin_nox_linearsystem.hpp, src/solver_nonlin_nox/4C_solver_nonlin_nox_linearsystem_base.cpp, src/solver_nonlin_nox/4C_solver_nonlin_nox_linearsystem_base.hpp, src/structure/4C_structure_timint_noxlinsys.cpp, src/structure/4C_structure_timint_noxlinsys.hpp
This method is used in a single place and does there quite a strange thing: https://github.com/trilinos/Trilinos/blob/8cea8978b961ed2c52ab41c223d9268d6348e40b/packages/nox/src-epetra/NOX_Epetra_Group.C#L388-L391. So we can just mock it for all our linear systems.
#1077, #1098
=> Mock method `NOX::Epetra::LinearSystem::setJacobianOperatorForSolve()`

src/core/io/src/4C_io_exodus.cpp, src/core/io/src/4C_io_exodus.hpp, src/core/io/src/4C_io_mesh.cpp, src/core/io/src/4C_io_mesh.hpp, src/core/io/src/4C_io_meshreader.cpp, src/core/io/src/4C_io_meshreader.hpp, src/core/io/tests/4C_io_exodus_test.cpp, src/global_data/4C_global_data_read.cpp, src/global_legacy_module/4C_global_legacy_module_validparameters.cpp
These changes generalize the exodus intermediate input representation so that it can also be used for other mesh formats. The data structure now contains all the data, the mesh reader expects to build the 4C discretization.
I have a small draft for vtu file input, which are a couple of lines then (using the vtk c++ library).
Part of #825
=> Generalize external mesh input

cmake/functions/four_c_testing_functions.cmake
I was astonished that we do not delete the output of our tutorials during the test_cleanup phase. Thus, this PR suggests removing this data during the cleanup
=> Remove output of tutorials during test_cleanup

src/core/io/src/4C_io_input_spec_builders.hpp, src/core/io/src/4C_io_input_spec_validators.hpp, src/global_legacy_module/4C_global_legacy_module_validmaterials.cpp, src/mat/4C_mat_muscle_combo.cpp, src/mat/4C_mat_muscle_giantesio.cpp, src/mat/4C_mat_muscle_weickenmeier.cpp, src/mat/4C_mat_stvenantkirchhoff.cpp, src/mat/elast/4C_mat_elast_isomuscle_blemker.cpp
- Use `Core::IO::InputSpecBuilders::Validators` to validate:
- **St. Venant–Kirchhoff material model** (commit 1)  
- **All muscle materials** (commits 2 + 3, to be squashed/merged together)  
- Fix a documentation error in `Core::IO::InputSpecBuilders::deprecated_selection` (commit 4).  
I often use:  
```cpp
using namespace Core::IO::InputSpecBuilders::Validators;
auto positive_or_zero_validator =
in_range<double>(0.0, std::numeric_limits<double>::max());
```
Should we introduce a `positive_or_zero()` helper just as we have the `positive()` helper function?
=> Validate muscle and St. Venant Kirchhoff material input via InputSpecBuilders::Validators

CONTRIBUTING.md
As the title states.
The link to the documentation of testing was obsolete. I think this new link is supposed to be the target.
[https://4c-multiphysics.github.io/4C/documentation/developer_guide/testing.html](https://4c-multiphysics.github.io/4C/documentation/developer_guide/testing.html)
=> Fix typo and doc link in CONTRIBUTING.md

src/structure_new/src/output/4C_structure_new_gauss_point_data_output_manager.cpp
This avoids using the same send and receive addresses for MPI_Allreduce calls in the gauss point data output manager, which is not in line with MPI standards and doesn't work for intel-mpi. 
none
=> Fix Gauss point data output manager MPI implementation

src/core/utils/benchmark_tests/stl_extension/4C_utils_flat_vector_vector_benchmark.cpp, src/core/utils/benchmark_tests/stl_extension/CMakeLists.txt
Follows #1231 
Current results:
```
Benchmark                         Time             CPU   Iterations
-------------------------------------------------------------------
flat_vector_vector_naive        132 ns          132 ns      5164265
flat_vector_vector_opt         88.7 ns         88.7 ns      7853843
```
where `naive` is a `vector<vector>` and `opt` is our data structure.
Can be enhanced with further benchmarks in the future.
=> Add benchmark for FlatVectorVector

src/fsi/src/monolithic/nonlinear_solver/4C_fsi_nox_group.cpp, src/fsi/src/monolithic/nonlinear_solver/4C_fsi_nox_linearsystem.hpp, src/fsi/src/partitioned/nonlinear_solver/4C_fsi_nox_mpe.cpp, src/fsi/src/partitioned/nonlinear_solver/4C_fsi_nox_sd.cpp, src/solver_nonlin_nox/4C_solver_nonlin_nox_constraint_group.cpp, src/solver_nonlin_nox/4C_solver_nonlin_nox_constraint_group.hpp, src/solver_nonlin_nox/4C_solver_nonlin_nox_group.cpp, src/solver_nonlin_nox/4C_solver_nonlin_nox_group.hpp, src/solver_nonlin_nox/4C_solver_nonlin_nox_group_base.cpp, src/solver_nonlin_nox/4C_solver_nonlin_nox_group_base.hpp, src/solver_nonlin_nox/4C_solver_nonlin_nox_linearsystem_base.hpp, src/solver_nonlin_nox/4C_solver_nonlin_nox_singlestep_group.cpp, src/solver_nonlin_nox/4C_solver_nonlin_nox_solver_ptc.cpp, src/structure_new/src/4C_structure_new_timint_basedataglobalstate.cpp, src/structure_new/src/implicit/4C_structure_new_impl_generic.hpp, src/structure_new/src/implicit/4C_structure_new_timint_implicit.cpp, src/structure_new/src/predict/4C_structure_new_predict_tangdis.cpp
This PR implements our own group class `GroupBase` that replaces `NOX::Epetra::Group` from Trilinos. Effectively, it reproduces functionality of the latter with the following essential modifications:
- Remove method `getNormLastLinearSolveResidual()` - it is mainly used in the single place of NOX, inside `NOX::Direction::ModifiedNewton::rescueBadNewtonSolve()` which attempts to proceed to the next time step even if the convergence tests failed but the "accuracy" measure was not so bad. We have never used this option, and in general, it does not look robust to me.
- Remove everything related to preconditioners since we build them outside of the group.
- Remove method computeNormNewtonSolveResidual() as it mainly provides information for `getNormLastLinearSolveResidual()`.
- Remove data …
=> Implement `GroupBase` to replace `NOX::Epetra::Group`

src/scatra/4C_scatra_timint_implicit.cpp, src/scatra/4C_scatra_timint_implicit.hpp
This pr removes an unused function in the scatra framework.
Following #1296
=> Remove unused function in scatra framework

src/core/io/src/4C_io_input_spec_builders.hpp, src/core/io/src/4C_io_input_spec_builders.templates.hpp, src/core/io/tests/4C_io_input_spec_test.cpp
Provide symbolic_expression in a separate template file. This should cut down on compile time again, since `input_spec_builders.hpp` transitively included Sacado (which is very expensive to include).
=> Move expensive InputSpecBuilders

src/beaminteraction/src/4C_beaminteraction_beam_to_beam_point_coupling_pair.cpp, src/beaminteraction/src/4C_beaminteraction_beam_to_beam_point_coupling_pair.hpp
Refactor the beam-to-beam point couplings. The code produces the same results, but is adapted such that the actual evaluation of the coupling constraints is moved to the methods `evaluate_positional_coupling` and `evaluate_rotational_coupling`, allowing for an easy extension to different beam theories. Where easily possible, analytic derivatives are used. Furthermore, the penalty regularisation is refactored such that it is easy to use these couplings directly with a Lagrange multiplier method.
=> Refactor beam-to-beam point couplings

src/core/utils/src/numerics/4C_utils_fad.hpp, src/core/utils/tests/numerics/4C_utils_fad_test.cpp
Add functionality to remap the indices of depended FAD derivatives.
Basically, one can compute AD values with a certain number and ordering of dependent variables and then convert that variable to another AD variable with a different number and ordering of dependent variables.
This is needed to enable a simple averaged nodal normals / tangent smoothing implementation.
=> Add remapping function for AD types

src/core/fem/src/discretization/4C_fem_discretization.cpp, src/core/fem/src/discretization/4C_fem_discretization.hpp, src/core/io/src/4C_io_exodus.cpp, src/core/io/src/4C_io_exodus.hpp, src/core/io/src/4C_io_mesh.cpp, src/core/io/src/4C_io_mesh.hpp, src/core/io/src/4C_io_meshreader.cpp, src/core/io/src/4C_io_meshreader.hpp, src/core/io/src/4C_io_vtu_reader.cpp, src/core/io/src/4C_io_vtu_reader.hpp, src/core/io/tests/4C_io_exodus_test.cpp, src/core/io/tests/4C_io_mesh_test.cpp, src/core/io/tests/4C_io_vtu_test.cpp, src/core/utils/src/stl_extension/4C_utils_owner_or_view.hpp, src/global_data/4C_global_data_read.cpp
This PR introduces a distinctions between `RawMesh` which is close to a mesh file, and `Mesh` which is an abstraction on top of `RawMesh`. This enables us to implement filtering operations on a mesh, e.g., filtering by the `cell_block_id`. Filtering is useful for all kinds of coupled physics, where one mesh file contains all the info, but we do not constantly want to check which pieces we need from the mesh. Instead, we filter the mesh once and then process the whole (filtered) mesh.
=> Allow to filter Mesh input

.github/workflows/docker_prebuilt_4c.yml
The prebuilt 4C docker image is always built and tagged as `main` even
if the tests fail. This better reflects the tag name `main` as the
docker image reflects the current state on main.
If the nightly tests succeed, this image gets the tag `stable`. So, the
tag `stable` reflects the last state where the tests were successful.
See issue https://github.com/4C-multiphysics/4C/issues/1134.
**Breaking change**: This is a breaking change because it changes the behavior of the Docker image. In the `main` image, the tests may not work. The previous `main` tag is now called `stable`. The `stable` image is the last state where the tests were successful.
@sebproell @amgebauer It would also be possible to use the REST API to query if the build in the nightly pipeline was successful. If the build …
=> 1134 always build prebuilt 4c image

.github/workflows/docker_prebuilt_4c.yml
The prebuilt 4C minimal image was erroneously pushed as `4c` and not `4c-minimal`.
Copy-pasta error. Sorry.
=> Fix erroneous docker image name for 4c-minimal

src/core/fem/src/general/utils/4C_fem_general_utils_fem_shapefunctions.hpp
Instead of the vector type itself, the shape functions now take a span so that it can easier be used with other types, for example `std::vector`.
=> Let shape functions take a span
