- .github/workflows/checkcode.yml
Why does this check actually not fail on Gitlab?
@sebproell @ppraegla
> Don't run no-commit-to-branch in CI

- .github/actions/build_4C/action.yml
- .github/actions/configure_4C/action.yml
- .github/workflows/buildtest.yml
- .gitlab/CODEOWNERS
Create composite actions to reuse configure and build 4C.
> Create reusable configure and build action

- .github/actions/configure_4C/action.yml
- .github/workflows/checkcode.yml
- presets/docker/CMakePresets.json
Extend codecheck workflow with clang-tidy and verify-headers
> Extend codecheck with clang-tidy and verify-headers

- .github/workflows/documentation.yml
Add workflow for Doxygen and Readthedocs generation. Currently also contains the changes from #4
> Add workflow for documentation

- .github/workflows/buildtest.yml
Test a simple separation of build and test. Probably, we want to do it a bit smarter.
> Separate build and test jobs

- .github/workflows/documentation.yml
Deploy doxygen and readthedocs to pages on main branch.
> Deploy documentation to Github pages

- .github/workflows/buildtest.yml
- .github/workflows/documentation.yml
Enable to use ccache in build stage between jobs with the same preset
> Use ccache in build-stage

- .github/workflows/deploy.yml
> Fix deployment of documentation on main across workflows

- .github/workflows/buildtest.yml
- apps/pre_exodus/4C_pre_exodus_writedat.cpp
Nice setup, @amgebauer and @ppraegla! This was trivial to add.
> CI: add clang 18 build and minimal test run

- .github/workflows/nightly_tests.yml
Adds the following jobs:
* gcc9_build + test
* clang18_build + test
* gcc9_asan_build + test
Missing:
* assertion-jobs
> Add full tests every night

- .github/actions/configure_4C/action.yml
- .github/workflows/buildtest.yml
- .github/workflows/nightly_tests.yml
> Don't setup Python dev-venv in Github workflows

- .github/actions/check_docker_build_required/action.yml
- .github/actions/compute-and-check-dependencies-hash/action.yml
- .github/workflows/buildtest.yml
- .github/workflows/checkcode.yml
- .github/workflows/docker.yml
- .github/workflows/documentation.yml
- .github/workflows/nightly_tests.yml
- docker/README.md
- docker/compute_dependencies_hash.sh
- tests/testconfig/.gitlab-ci.yml
Add a small script that computes the hash. It is reused at all places where we need to do so.
Please carefully check whether I did everything correct, especially on those checks that didn't run for these changes.
> Remove duplication of dependencies hash generator

- cmake/functions/four_c_auto_define_module.cmake
- src/scatra_ele/4C_scatra_ele_calc.cpp
- src/scatra_ele/4C_scatra_ele_calc.inst.hpp
- src/scatra_ele/4C_scatra_ele_calc_OD.cpp
- src/scatra_ele/4C_scatra_ele_calc_lsreinit.cpp
- src/scatra_ele/4C_scatra_ele_calc_no_physics.cpp
- src/scatra_ele/4C_scatra_ele_calc_no_physics.inst.hpp
- src/scatra_ele/4C_scatra_ele_calc_service_general.cpp
- src/scatra_ele/4C_scatra_ele_calc_service_no_physics.cpp
- src/scatra_ele/4C_scatra_ele_calc_service_stabilization.cpp
- src/scatra_ele/4C_scatra_ele_calc_service_turbulence.cpp
- src/so3/4C_so3_poro.cpp
- src/so3/4C_so3_poro.inst.hpp
- src/so3/4C_so3_poro_evaluate.cpp
- src/so3/4C_so3_poro_p1.cpp
- src/so3/4C_so3_poro_p1.inst.hpp
- src/so3/4C_so3_poro_p1_evaluate.cpp
- src/so3/4C_so3_poro_scatra.cpp
- src/so3/4C_so3_poro_scatra.inst.hpp
- src/so3/4C_so3_poro_scatra_evaluate.cpp
- src/so3/so3_plast/4C_so3_plast_ssn.cpp
- src/so3/so3_plast/4C_so3_plast_ssn_evaluate.cpp
- src/so3/so3_plast/4C_so3_ssn_plast.inst.hpp
> Rename files with instantiations to .inst.hpp

- src/mat/4C_mat_scatra_multiscale_gp.cpp
- src/mat/4C_mat_scatra_multiscale_gp.hpp
Might fix https://gitlab.lrz.de/baci/baci/-/issues/1347
FYI @maxfirmbach
> Fix a bug where multiscale mat is freed too late

- README.md
- utilities/assets/badges/documentation_doxygen.svg
- utilities/assets/badges/documentation_readthedocs.svg
- utilities/assets/badges/website_badge.svg
Added the current 4C logo as a replacement to the name 4C in the header
Also saved the static badges into assets and added them to the readme
#42
> Extend badges in readme and add logo

- src/mat/4C_mat_multiplicative_split_defgrad_elasthyper.cpp
- src/mat/4C_mat_multiplicative_split_defgrad_elasthyper.hpp
- unittests/mat/4C_multiplicative_split_defgrad_elasthyper_test.cpp
The current management of the struct instance `kinematic_quantities` in `src/mat/4C_mat_multiplicative_split_defgrad_elasthyper.cpp` is not optimal, as some of its variables are modified during the associated method calls, while others should remain `const` throughout.  Additionally, this struct also contains both elastic stiffness components and stress factors, which are not kinematic quantities. This PR addresses these issues, and  the following work has been performed:
- Removed the elastic stiffness components from `KinematicQuantities`.
- Removed the $\gamma_i$ and $\delta_i$ stress factors  from `KinematicQuantities` and added them to a separate `StressFactors` struct. 
- Aside from `evaluate_kin_quant_elast`, which evaluates all of its variables, the struct instance of …
> Optimize struct handling in MulitplicativeSplitDefgradElastHyper material

- doc/doxygen/index.doc
I merged #108 prematurely, so this PR delivers changes that came up during review of #108.
Follows #108.
> Slightly rephrase content of doxygen main page

- src/core/fem/src/condition/4C_fem_condition_definition.cpp
- src/core/fem/src/condition/4C_fem_condition_definition.hpp
- src/core/io/src/4C_io_linecomponent.cpp
- src/core/io/src/4C_io_linecomponent.hpp
- src/inpar/4C_inpar_validconditions.cpp
- src/inpar/4C_inpar_validmaterials.cpp
Remove unused features. This helps getting a better overview on what is required for #113.
> Remove unused print functions

- apps/create_rtdfiles/4C_create_rtdfiles_utils.cpp
- src/core/io/src/4C_io_input_spec_builders.cpp
- src/core/io/src/4C_io_input_spec_builders.hpp
- src/global_data/4C_global_data_read.cpp
- src/inpar/4C_inpar_validmaterials.cpp
- src/mat/4C_mat_electrode.cpp
- src/mat/4C_mat_fluidporo_singlephase.cpp
- src/mat/4C_mat_materialdefinition.cpp
- src/mat/4C_mat_materialdefinition.hpp
- src/mat/4C_mat_muscle_combo.cpp
- src/mat/4C_mat_scatra_reaction.cpp
> Use InputSpec in internals of MaterialDefinition

- presets/lnm/cluster/CMakePresets.json
Update the LNM Cluster config to actually use the new GCC 13.2 compiler
Also add FOUR_C_OPENMPI_ROOT to remove the necessity that each user loads the module within their bash.rc file
> Update LNM cluster presets

- src/solid_3D_ele/4C_solid_3D_ele_calc.cpp
- src/solid_3D_ele/4C_solid_3D_ele_calc_lib.hpp
- src/solid_3D_ele/4C_solid_3D_ele_calc_lib_fbar.hpp
- src/solid_3D_ele/4C_solid_3D_ele_calc_lib_nitsche.hpp
- src/solid_3D_ele/4C_solid_3D_ele_calc_mulf.hpp
- src/solid_3D_ele/4C_solid_3D_ele_factory.cpp
- src/solid_3D_ele/4C_solid_3D_ele_formulation.hpp
- src/solid_poro_3D_ele/4C_solid_poro_3D_ele_calc_lib.hpp
- src/solid_poro_3D_ele/4C_solid_poro_3D_ele_calc_pressure_velocity_based.cpp
- src/solid_scatra_3D_ele/4C_solid_scatra_3D_ele_calc_lib_nitsche.hpp
- src/solid_scatra_3D_ele/4C_solid_scatra_3D_ele_factory.cpp
Use c++20 constraints and concepts syntax instead of `std::enable_if_t<>`- and `std::void_t<>`-constructs
> Use requires in new solid elements

- cmake/python/set_up_python.cmake
@georghammerl could you check whether this already fixes the problem?
Closes #266
> Remove -U from setup virtual environment

- src/core/io/src/4C_io.cpp
- src/core/io/src/4C_io_hdf.cpp
- src/core/io/src/4C_io_hdf.hpp
I noticed these flags which we are for sure not allowed to fiddle with.
> Remove hacky HDF5 flags and update to newer API

- src/so3/4C_so3_surface.hpp
- src/so3/4C_so3_surface_evaluate.cpp
These actions are neither used nor referenced in 4C.
> Remove unused actions from so3_surface

- tests/input_files/xml/multigrid/fluid_solid_ale.xml
Specify the direct solver backend via the xml file. This mainly shall document the parameter.
> Update FSI preconditioner template to specify block direct solver on MueLu coarse level

- src/core/io/src/4C_io_input_spec_builders.cpp
- src/core/io/src/4C_io_input_spec_builders.hpp
- src/core/io/tests/4C_io_input_spec_test.cpp
- src/inpar/4C_inpar_s2i.cpp
A few things uncovered by @gilrrei while working on the schema file
> Minor fixes and asserts in InputSpecs

- tests/input_files/poro_new_solid_nitsche_contact3D_twoelem_new_struc.dat
- tests/input_files/poro_solid_nitsche_contact3D_twoelem_twosided_new_struc.dat
- tests/input_files/poro_solid_nitsche_contact3D_twoelem_wonopen_new_struc.dat
> Fix failing main branch due to wrong input files

- src/core/io/src/4C_io_input_parameter_container.cpp
- src/core/io/src/4C_io_input_parameter_container.hpp
- src/core/io/tests/4C_io_input_parameter_container_test.cpp
I need this to read key-values with `InputSpec` into `InputParameterContainer` and later convert to a ParameterList which is expected in all existing code.
> Conversion of InputParameterContainer to Teuchos::PL

- apps/global_full/4C_global_full_inp_control.cpp
- apps/pre_exodus/4C_pre_exodus_validate.cpp
- src/core/io/src/4C_io_input_file.cpp
- src/core/io/src/4C_io_input_file.hpp
Fix a bug in the input file parsing mechanism where an unknown section was not recorded properly. If the unknown section is not known it was not correctly set.
For example, `PROBLEM TYP` was not recognized and the default values were used.
> Fix print_unknown_section

- CONTRIBUTING.md
- doc/README.md
This is a first draft of rewriting the CONTRIBUTING.md. It is very close to the one from [Queens](https://github.com/queens-py/queens/blob/main/CONTRIBUTING.md).
Closes #171
> Update the CONTRIBUTING.md

- src/structure_new/src/model_evaluator/4C_structure_new_model_evaluator_structure.cpp
- src/structure_new/src/model_evaluator/4C_structure_new_model_evaluator_structure.hpp
- src/structure_new/src/output/4C_structure_new_discretization_runtime_output_params.cpp
- src/structure_new/src/output/4C_structure_new_discretization_runtime_output_params.hpp
Manual export to column map is unnecessary and thus removed. Furthermore, some minor beauty changes in related files.
> Minor cleanup new structure vtk output

- src/core/io/src/4C_io_input_file.cpp
- src/core/io/src/4C_io_input_file.hpp
- src/core/io/src/4C_io_input_spec_builders.cpp
- src/core/io/src/4C_io_value_parser.cpp
- src/core/io/src/4C_io_value_parser.hpp
- src/core/io/tests/4C_io_input_file_test.cpp
- src/core/io/tests/4C_io_input_spec_test.cpp
- src/core/io/tests/4C_io_value_parser_test.cpp
Two small things that came up when working with the input mechanism.
> Minor enhancements and fixes in new input mechanism

- src/adapter/4C_adapter_scatra_base_algorithm.cpp
- src/contact/4C_contact_manager.cpp
- src/contact/4C_contact_meshtying_manager.cpp
- src/contact/4C_contact_meshtying_strategy_factory.cpp
- src/elemag/4C_elemag_dyn.cpp
- src/scatra/4C_scatra_timint_elch_scl.cpp
- src/ssi/4C_ssi_utils.cpp
- src/ssti/4C_ssti_algorithm.cpp
Should address most of the errors I get in #343
> Set enum parameters directly instead of via string

- CODE_OF_CONDUCT.md
> Add link to list of maintainers to code of conduct

- src/reduced_lung/4C_reduced_lung_main.cpp
I used the wrong vector for a postprocessing step, which led to a wrong access ID with more ranks.
> Fix asan in reduced lung

- .github/actions/build_dependencies/action.yml
- .github/workflows/docker.yml
- .github/workflows/docker_prebuilt_4c.yml
The build attestation can be used to verify where and how the docker images were built (See [here](https://docs.github.com/en/actions/security-for-github-actions/using-artifact-attestations/using-artifact-attestations-to-establish-provenance-for-builds)). Generally, this is nice to have. But this also generates a lot of noise in the package registry. And the suggested docker install command does not work because the latest entry in the package registry is an attestation instead of the image which cannot be pulled, e.g. https://github.com/4C-multiphysics/4C/pkgs/container/4c-dependencies-ubuntu24.04. Also, I find the verification process cumbersome (it only works via GitHub CLI), e.g.
```
$ gh attestation verify oci://ghcr.io/4c-multiphysics/4c:latest --repo 4C-multiphysics/4C
Loaded …
```
> CI: remove docker build attestation

- src/adapter/4C_adapter_str_structure.cpp
- src/core/fem/src/discretization/4C_fem_discretization.cpp
- src/core/linear_solver/src/method/4C_linear_solver_method.hpp
- src/core/linear_solver/src/method/4C_linear_solver_method_iterative.cpp
- src/core/linear_solver/src/method/4C_linear_solver_method_linalg.cpp
- src/core/linear_solver/src/preconditioner/4C_linear_solver_preconditioner_muelu.cpp
- src/core/linear_solver/src/preconditioner/4C_linear_solver_preconditioner_muelu.hpp
- src/inpar/4C_inpar_solver.cpp
- src/structure/4C_structure_timint_impl.cpp
- src/structure_new/src/linear_solver/4C_structure_new_solver_factory.cpp
- tests/input_files/contact3D_sp_dual_simple.dat
- tests/input_files/contact3D_sp_std_braess_sarazin.dat
- tests/input_files/contact3D_sp_std_simple.dat
- tests/input_files/contact3D_sp_std_uzawa.dat
- tests/input_files/meshtying3D_sp_dual_simple.dat
- tests/input_files/meshtying3D_sp_std_braess_sarazin.dat
- tests/input_files/meshtying3D_sp_std_simple.dat
- tests/input_files/meshtying3D_sp_std_uzawa.dat
Reduces the number of MueLu interfaces to be maintained by passing the contact preconditioning through the regular MueLu interface.
> Replace contact AMG preconditioner with general MueLu implementation

- src/inpar/4C_inpar_thermo.cpp
- src/thermo/src/element/4C_thermo_ele_impl.cpp
- src/thermo/src/implicit/4C_thermo_timint.cpp
This PR removes some remains of the explicit time integration in `thermo`.
Follows #294 #347
> [thermo] Remove explicit Euler enum

- src/core/io/src/4C_io_input_file.cpp
- src/global_data/4C_global_data_read.cpp
> InputFile: allow arbitrary FUNCT<n> sections

- src/core/io/src/4C_io_yaml.hpp
- src/core/io/tests/4C_io_input_spec_test.cpp
Small mistake when checking the value of a node.
> Fix reading "none" values from yaml

- src/core/fem/src/condition/4C_fem_condition_definition.cpp
- src/core/io/src/4C_io_input_spec_builders.cpp
- src/core/io/src/4C_io_input_spec_builders.hpp
- src/core/io/tests/4C_io_input_spec_test.cpp
> Better errors when entering wrong input

- src/global_legacy_module/4C_global_legacy_module_validmaterials.cpp
- src/mat/4C_mat_plasticgtn.cpp
- src/mat/4C_mat_plasticgtn.hpp
- tests/input_files/mat_gtn_patch_test.dat
- tests/input_files/mat_gtn_solid_necking_bar_with_f0_fc_h8.dat
- tests/input_files/mat_gtn_solid_necking_bar_with_f0_h8.dat
- tests/list_of_tests.cmake
Improve some aspects of the local coupled damage-plasticity model GTN:
+ Fix the calculation of derivatives in case of using hardening function.
+ Add stabilization parameter for effective damage.
+ Add example with damage limit (fC).
!2205, !2465 (old gitlab) #353
> Improve GTN

- src/fluid_xfluid/4C_fluid_xfluid.cpp
- src/xfem/4C_xfem_coupling_fpi_mesh.cpp
- src/xfem/4C_xfem_coupling_fpi_mesh.hpp
- src/xfem/4C_xfem_coupling_mesh.cpp
- src/xfem/4C_xfem_mesh_projector.cpp
- src/xfem/4C_xfem_mesh_projector.hpp
- src/xfem/4C_xfem_xfluid_contact_communicator.cpp
- src/xfem/4C_xfem_xfluid_contact_communicator.hpp
- src/xfem/4C_xfem_xfluid_timeInt.cpp
- src/xfem/4C_xfem_xfluid_timeInt.hpp
In this PR, some functions related to Gmsh output are deleted. These functions are not covered by the coverage report and therefore untested. Some output was also deleted since it does not provide meaningful information in case something goes wrong, e.g. in a failed cut scenario, it only prints the failed cells but does not help understanding the real issue and how to solve it.
Related to #398, #201
> Remove gmsh functions from xfem

- cmake/functions/four_c_testing_functions.cmake
> Ignore memory leaks (from MPI) for yaml convert

- src/core/io/src/4C_io_input_spec_builders.hpp
- src/core/io/tests/4C_io_input_spec_test.cpp
In reference to https://github.com/4C-multiphysics/4C/pull/424#issuecomment-2677096857
> Improve error for wrong selection value in dat

- src/core/io/src/4C_io_input_file.cpp
Yaml files can start with `---` to mark the beginning of a document. This didn't work before. The absurd thing is that we cannot test it since our formatted `yamlfmt` either wants to insert the `---` marker everywhere or nowhere. There is no drawback to inserting it in all our yaml files but it feels wrong to do that for the purpose of having a few test files. Opinions?
> Allow to read yaml files with --- document markers

- src/so3/4C_so3_poro.hpp
- src/so3/4C_so3_poro_p1_evaluate.cpp
This is never referenced and can be be removed.
> Remove unused interpolate_porosity_to_given_point

- src/solid_poro_3D_ele/4C_solid_poro_3D_ele_calc_lib.hpp
This method is can be replaced by simpler methods from Core.
Currently, it also handles weird dof-handling for the solid-poro-p1 formulation. If we need it, we can implement this in the p1-formulation or better, not append the porosity to the displacements but rather to its own global state vector.
> Remove specialized method from solid poro

- src/solid_poro_3D_ele/4C_solid_poro_3D_ele_calc_lib.hpp
- src/solid_poro_3D_ele/4C_solid_poro_3D_ele_pressure_velocity_based.cpp
> Fix problems in input of solid_poro

- doc/readthedocs/4Ccommunity.rst
- doc/readthedocs/community_roles.rst
- doc/readthedocs/developer_life_cycle.rst
- doc/readthedocs/index.rst
Insert brief description of our 4C community with its different roles and a developer life cylce statement to clarify when developer status is assigned.
@4C-multiphysics/maintainer
> Add 4C community description

- src/core/comm/src/4C_comm_pack_helpers.hpp
- src/core/comm/tests/4C_comm_pack_unpack_test.np3.cpp
Cherry-picked from #471 with some additional fixes of doxygen.
> Implement optional pack/unpack helper

- utilities/create_json_schema.py
I forgot to add the parameter description for the primitive types
> Add missing parameter description

- src/core/io/src/4C_io_input_spec_builders.hpp
- src/core/io/tests/4C_io_input_spec_test.cpp
Together with @gilrrei and @lauraengelhardt, we identified a common use case when creating InputSpecs. One often wants to selectively activate more parameters based on the value of a certain parameter. This PR enables that based on strings. I am a bit reluctant to add another overload taking a enum-to-string mapping, and would rather want to use magic_enum for that, see #465.
> InputSpec: new selection for common use case

- src/poromultiphase_scatra/4C_poromultiphase_scatra_function.cpp
- tests/input_files/new_solidporo_pressure_based_ele_poromultielastscatra_3D_hex8_mono_tumor.dat
- tests/input_files/new_solidporo_pressure_based_ele_poromultielastscatra_3D_hex8_nodetopoint_artery_airway_coupling_mono.dat
- tests/input_files/poromultielastscatra_2D_quad4_haptotaxis.dat
- tests/input_files/poromultielastscatra_2D_quad4_hyperthermia.dat
- tests/input_files/poromultielastscatra_2D_quad4_linebased_artery_coupling_vessel_collapse.dat
- tests/input_files/poromultielastscatra_2D_quad4_linebased_artery_coupling_vessel_collapse_free_hanging.dat
- tests/input_files/poromultielastscatra_2D_quad4_nodetopoint_artery_airway_coupling_mono.dat
- tests/input_files/poromultielastscatra_2D_quad4_tumor_angiogenesis.dat
- tests/input_files/poromultielastscatra_3D_hex8_mono_tumor.dat
- tests/input_files/poromultielastscatra_3D_hex8_nodetopoint_artery_airway_coupling_mono.dat
> Remove numparams from poromultiphasescatra functions

- apps/global_full/CMakeLists.txt
Remove the last remnant of BACI - the symbolic link to the 4C executable
> Remove BACI symbolic link

- src/contact/4C_contact_interface.cpp
- src/core/binstrategy/4C_binstrategy.cpp
- src/core/fem/src/condition/4C_fem_condition_periodic.cpp
- src/core/fem/src/discretization/4C_fem_discretization_partition.cpp
- src/core/io/src/4C_io_gridgenerator.cpp
- src/core/io/src/4C_io_meshreader.cpp
- src/core/linalg/src/sparse/4C_linalg_graph.cpp
- src/core/linalg/src/sparse/4C_linalg_graph.hpp
- src/core/linalg/src/sparse/4C_linalg_sparsematrix.cpp
- src/core/linalg/src/sparse/4C_linalg_utils_sparse_algebra_manipulation.cpp
- src/core/linalg/src/sparse/4C_linalg_utils_sparse_algebra_math.cpp
- src/core/linalg/tests/4C_linalg_utils_sparse_algebra_manipulation_test.np2.cpp
- src/core/rebalance/src/4C_rebalance_graph_based.cpp
- src/fsi/src/partitioned/4C_fsi_partitioned.cpp
Renames the functions within the class `4C_linalg_graph` according to a clang-tidy compatible format.
The changes are now in separate commits for an easy review process and will be squashed after the first round.  
Part of #414
> [epetra] Apply clang-tidy in graph wrapper

- .gitignore
As suggested by @sebproell, we extended the gitignore file.
> Add additional inputs to gitignore

- src/core/fem/src/general/element/4C_fem_general_element_definition.hpp
- src/core/io/src/4C_io_input_file.cpp
- src/core/io/src/4C_io_input_file.hpp
- src/global_data/4C_global_data_read.cpp
We know many things about the elements we can input, so write it out in the metadata file.
> Emit knowledge about elements to metadata

- tests/list_of_tests.cmake
> Disable failing test with unclear fix

- README.md
After the inofficial logo was wrongfully added in #87 and removed we can now finally add the correct logo
~~I need to check if the dark mode version also works on github~~ it works
#87
> Add 4C logo to readme

- src/core/io/src/4C_io_input_file.cpp
So far we always copied the whole internal representation of the yaml tree to all ranks. That is certainly not ideal. This PR only copies sections if they are small. The large sections (which will vanish eventually with #60) are not copied. They are only processed on rank 0 in the code.
@ppraegla Can you give this a try for the large particle example you mentioned?
FYI @isteinbrecher
> Only communicate small sections when reading yaml

- src/core/linalg/src/sparse/4C_linalg_map.hpp
> Remove an expensive include from LinAlg::Map

- README.md
- utilities/assets/badges/documentation_documentation.svg
Following #523 this PR fixes the wrong formatting and file name of the docu badge - it bugged me too much to ignore it longer😅
#523
> Fix documentation badge

- src/global_data/4C_global_data_read.cpp
- src/particle_engine/4C_particle_engine_enums.cpp
- src/particle_engine/4C_particle_engine_enums.hpp
- src/particle_engine/4C_particle_engine_particlereader.cpp
- src/particle_engine/4C_particle_engine_particlereader.hpp
Useful for FourCIPP
FYI @gilrrei
> Enhance legacy section metadata with more info

- apps/post_monitor/4C_post_monitor.hpp
- src/ale/4C_ale_resulttest.cpp
- src/art_net/4C_art_net_artery_resulttest.cpp
- src/core/fem/src/general/element/4C_fem_general_element.hpp
- src/core/io/src/4C_io_gridgenerator.cpp
- src/core/utils/src/result_test/4C_utils_result_test.cpp
- src/core/utils/src/result_test/4C_utils_result_test.hpp
- src/fsi/src/utils/4C_fsi_resulttest.cpp
- src/lubrication/src/4C_lubrication_resulttest.cpp
- src/membrane/4C_membrane_scatra.cpp
- src/particle_algorithm/4C_particle_algorithm_result_test.cpp
- src/particle_rigidbody/4C_particle_rigidbody_result_test.cpp
- src/particle_wall/4C_particle_wall_result_test.cpp
- src/porofluid_pressure_based/4C_porofluid_pressure_based_resulttest.cpp
- src/red_airways/4C_red_airways_resulttest.cpp
- src/rigidsphere/4C_rigidsphere_input.cpp
- src/solid_3D_ele/4C_solid_3D_ele_line.cpp
- src/ssti/4C_ssti_resulttest.cpp
- src/sti/4C_sti_resulttest.cpp
- src/structure/4C_structure_resulttest.cpp
- src/structure_new/src/utils/4C_structure_new_resulttest.cpp
- src/thermo/src/utils/4C_thermo_resulttest.cpp
Remove a rather expensive include from core headers.
> Remove a few InputParameterContainer includes

- apps/global_full/4C_global_full_control.cpp
> Warn when using a dat file in a 4C run

- apps/create_rtdfiles/4C_create_rtdfiles_utils.cpp
- apps/create_rtdfiles/4C_create_rtdfiles_wrapper.cpp
- cmake/configure/configure_Boost.cmake
- src/constraint_framework/4C_constraint_framework_submodelevaluator_mpc.hpp
- src/core/linalg/src/sparse/4C_linalg_view.hpp
- src/core/utils/src/string_utils/4C_utils_string.cpp
- src/core/utils/src/string_utils/4C_utils_string.hpp
- src/cut/4C_cut_find_cycles.hpp
- src/cut/4C_cut_pointgraph.cpp
I accidentally included a boost file in the LinAlg::View header, so I cleaned this dependency a little bit.
- Remove string functions that are trivial to write with std
- Remove unused includes
> Clean up boost dependency

- cmake/configure/configure_ArborX.cmake
- src/core/fem/src/geometric_search/4C_fem_geometric_search_access_traits.hpp
- src/core/fem/src/geometric_search/4C_fem_geometric_search_bvh.cpp
- src/core/fem/src/geometric_search/4C_fem_geometric_search_distributed_tree.cpp
This PR updates the `ArborX` hash to the most recent one and adjusts the API to deal with backwards compatibility issues.
Closes #291 #290
> [ArborX] Update ArborX hash and adjust API

- cmake/functions/four_c_testing_functions.cmake
- tests/list_of_tests.cmake
Required for #400 
@dharinib98 @mayrmt This should help you.
> Cmake: copy arbitray number of support files for framework tests

- src/core/io/src/4C_io_input_file.cpp
- src/core/io/src/4C_io_input_file.hpp
- src/core/io/src/4C_io_input_file_utils.cpp
The InputFile is now more flexible and these checks can go away.
> Allow non-required section in input files

- .github/workflows/nightly_tests.yml
In https://github.com/4C-multiphysics/fourcipp/issues/15 I want to update the metadata and schema file on a nightly basis.
Currently the metadata and schema file is only uploaded as an artifact with regular PR workflows. In my opinion we should upload it nightly and increase the retention days.
https://github.com/4C-multiphysics/fourcipp/issues/15
> Upload metadata and schema file nightly

- apps/global_full/4C_global_full_main.cpp
> Fix printing of Trilinos git SHA

- doc/documentation/developer_cmake.rst
- doc/documentation/developer_dirstructure.rst
- doc/documentation/installation.rst
Noticed while working on #676.
> Minor bugfixes in documentation

- doc/documentation/src/developer_guide/doxygen.rst
Let's remove the details of Doxygen and give some examples.
Follows #678
> Update documentation on doxygen with an example

- doc/documentation/src/developer_guide/developmentguide.rst
- doc/documentation/src/developer_guide/testing.rst
- Adapt to CMake changes
- Remove mentions of dat files #598
> Update testing docs

- src/reduced_lung/4C_reduced_lung_helpers.cpp
- src/reduced_lung/4C_reduced_lung_helpers.hpp
- src/reduced_lung/4C_reduced_lung_main.cpp
Adds a basic implementation for runtime Vtu output to `reduced_lung`. This will be extended with more features in the future when more models and better data structures are available.
I also renamed some variables along the way.
> Add vtu output to reduced lung

- src/reduced_lung/4C_reduced_lung_helpers.cpp
- src/reduced_lung/4C_reduced_lung_helpers.hpp
- src/reduced_lung/4C_reduced_lung_main.cpp
I used the wrong map for dof-access, similar to #363.
> Fix asan bug in reduced lung

- src/mat/4C_mat_scatra_multiscale_gp.cpp
> Make a check in scatra microscale independent of node numbering

- doc/doxygen/CMakeLists.txt
> CMake: set cache variables for MathJax in Doxygen

- README.md
Fix the links in the README.md.
> Fix broken documentation links in the README.md

- src/core/io/src/4C_io_exodus.cpp
- src/core/io/src/4C_io_exodus.hpp
- src/core/io/src/4C_io_meshreader.cpp
- src/core/io/tests/4C_io_exodus_test.cpp
- src/global_data/4C_global_data_read.cpp
> Remove unused features from Exodus::Mesh

- doc/documentation/src/installation/installation.rst
This pr adds a documentation of a possible git workflow to contribute to 4C with prs.
> Add documentation for a git workflow for development with prs

- src/core/utils/src/stl_extension/4C_utils_box.hpp
- src/solid_3D_ele/4C_solid_3D_ele_factory_lib.hpp
Make an implementation by @amgebauer available in `core`. I want to use to improve our Epetra wrappers and views.
> Add Box type for heap-allocated values

- src/beaminteraction/src/4C_beaminteraction_submodel_evaluator_crosslinking.cpp
- src/beaminteraction/src/4C_beaminteraction_submodel_evaluator_crosslinking.hpp
- src/constraint/4C_constraint_multipointconstraint2.cpp
- src/constraint/4C_constraint_multipointconstraint3.cpp
- src/constraint/4C_constraint_multipointconstraint3penalty.cpp
- src/core/binstrategy/4C_binstrategy.cpp
- src/core/binstrategy/4C_binstrategy_utils.cpp
- src/core/fem/src/condition/4C_fem_condition_periodic.cpp
- src/core/fem/src/condition/4C_fem_condition_periodic.hpp
- src/core/geometric_search/src/4C_geometric_search_matchingoctree.cpp
- src/core/geometric_search/src/4C_geometric_search_matchingoctree.hpp
- src/core/io/src/legacy/4C_io_legacy_table_iter.cpp
- src/cut/4C_cut_element.hpp
- src/cut/4C_cut_tetmesh.cpp
- src/fluid/4C_fluid_implicit_integration.cpp
- src/fluid_ele/4C_fluid_ele_calc_xfem_coupling_impl.hpp
- src/fsi_xfem/4C_fsi_xfem_coupling_comm_manager.cpp
- src/mat/4C_mat_damage.cpp
- src/mixture/4C_mixture_rule.hpp
- src/structure/4C_structure_timint_impl.cpp
- src/tsi/4C_tsi_partitioned.cpp
This removes all occurrences of "his" that are wrong. We did not have any occurrences of "her".
> Use correct English possessive pronouns

- src/structure_new/src/nonlinear_solver/4C_structure_new_nln_solver_nox.cpp
Reported by @bwirthl 
Caused by #798 
Would be avoided by #483
> Add missing include for older Trilinos versions

- apps/global_full/4C_global_full_cal_control.cpp
- src/porofluid_pressure_based_elast_scatra/4C_porofluid_pressure_based_elast_scatra_base.cpp
- src/porofluid_pressure_based_elast_scatra/4C_porofluid_pressure_based_elast_scatra_base.hpp
- src/porofluid_pressure_based_elast_scatra/4C_porofluid_pressure_based_elast_scatra_dyn.cpp
- src/porofluid_pressure_based_elast_scatra/4C_porofluid_pressure_based_elast_scatra_dyn.hpp
- src/porofluid_pressure_based_elast_scatra/4C_porofluid_pressure_based_elast_scatra_monolithic.cpp
- src/porofluid_pressure_based_elast_scatra/4C_porofluid_pressure_based_elast_scatra_monolithic.hpp
- src/porofluid_pressure_based_elast_scatra/4C_porofluid_pressure_based_elast_scatra_partitioned.cpp
- src/porofluid_pressure_based_elast_scatra/4C_porofluid_pressure_based_elast_scatra_partitioned.hpp
- src/porofluid_pressure_based_elast_scatra/4C_porofluid_pressure_based_elast_scatra_utils.cpp
- src/porofluid_pressure_based_elast_scatra/4C_porofluid_pressure_based_elast_scatra_utils.hpp
Follows #789, #726, #689 and #666
> Clean up PorofluidElastScatraBaseAlgorithm

- .mailmap
Updating my email address in the .mailmap.
Since my old work email address is not verified in my github profile, none of my commits can be attributed to me. This has led to some confusion in a couple of job interviews. Hoping that this will fix the issue, and that I will be shown as a contributor after 5 years in the (BACI) project.
> Change primary email address for Nora Hagmeyer

- src/core/linalg/src/dense/4C_linalg_tensor_internals.hpp
- src/core/linalg/src/dense/4C_linalg_tensor_meta_utils.hpp
- src/core/linalg/tests/4C_linalg_tensor_test.cpp
- unittests/common/unittest_utils/4C_unittest_utils_assertions_test.hpp
Allow comparison of tensors in unit tests
> Implement tensor comparison in unit tests

- cmake/setup_global_options.cmake
`RELWITHDEBINFO` is good for profiling and should have the same optimization level as `RELEASE`
> Use `-O3` for `RELWITHDEBINFO`

- src/fluid_turbulence/4C_fluid_turbulence_boxfilter.cpp
- src/fluid_turbulence/4C_fluid_turbulence_statistics_cha.cpp
> Avoid get_condition in fluid_turbulence

- src/core/io/src/4C_io_input_spec_builders.hpp
Fixing bug introduced with #890. 
FYI @maxfirmbach
> Bugfix in input_field_callback

- src/core/linalg/src/dense/4C_linalg_fixedsizematrix.hpp
- src/core/linalg/src/dense/4C_linalg_utlis_quaternion_interpolation.cpp
- src/core/linalg/src/dense/4C_linalg_utlis_quaternion_interpolation.hpp
- src/core/linalg/tests/4C_linalg_utils_quaternion_interpolation_test.cpp
This PR provides functions and classes for quaternion interpolation, including spherical linear interpolation (SLERP) and generalized SLERP for multiple quaternions with unit tests.
This class is required for tensor interpolation methods , see Satheesh et al., 2024, 10.1002/nme.7373
> Quaternion interpolation

- doc/documentation/src/tools/tools.rst
- tests/input_files/embeddedmesh_2d_hertzian_contact.yaml
- unittests/geometry_pair/4C_geometry_pair_line_to_volume_segmentation_geometry_functions_test.hpp
Following the naming change from MeshPy to BeamMe, all occurences across the code base are either removed or updated.
> Fix: rename meshpy to beamme

- src/core/comm/src/4C_comm_exporter.hpp
> Make Exporter work for unordered_map

- src/scatra_ele/4C_scatra_ele_calc_advanced_reaction.cpp
- src/scatra_ele/4C_scatra_ele_calc_advanced_reaction.hpp
- src/scatra_ele/4C_scatra_ele_calc_poro_reac_ECM.cpp
Removed some unnecessary return statements and clarified a comment in the advanced-reaction framework.
> Remove return statements and clarify comment

- src/core/utils/src/functions/4C_utils_symbolic_expression.cpp
> Fix UB in symbolic expression lexer

- src/beamcontact/4C_beamcontact_beam3contact_octtree.hpp
- src/mixture/4C_mixture_full_constrained_mixture_fiber.hpp
- src/post/4C_post_common.cpp
- src/sti/4C_sti_partitioned.cpp
- src/thermo/src/implicit/4C_thermo_timint.cpp
As a follow-up to the pub quiz during our workshop, I scanned the codebase for any inappropriate comments, language, wording... 
Spoiler: We are good! The word "shit" appears only once, and it was a typo.
> Professionalize language 

- src/core/comm/src/4C_comm_exporter.cpp
- src/core/fem/src/discretization/4C_fem_discretization_conditions.cpp
- src/ssi/4C_ssi_monolithic.cpp
- src/ssi/4C_ssi_monolithic_assemble_strategy.cpp
- src/ssi/4C_ssi_monolithic_assemble_strategy.hpp
- src/xfem/4C_xfem_condition_manager.cpp
Likely the first of a few PRs to fix the issues that #1033 uncovers. This one fixes all minimal tests.
> Fix bugs uncovered by _GLIBCXX_ASSERTIONS in minimal tests

- src/contact_constitutivelaw/4C_contact_constitutivelaw_brokenrational_contactconstitutivelaw.cpp
- src/contact_constitutivelaw/4C_contact_constitutivelaw_contactconstitutivelaw.cpp
- src/contact_constitutivelaw/4C_contact_constitutivelaw_cubic_contactconstitutivelaw.cpp
- src/contact_constitutivelaw/4C_contact_constitutivelaw_cubic_contactconstitutivelaw.hpp
- src/contact_constitutivelaw/4C_contact_constitutivelaw_interface.cpp
- src/contact_constitutivelaw/4C_contact_constitutivelaw_interface.hpp
- src/contact_constitutivelaw/4C_contact_constitutivelaw_linear_contactconstitutivelaw.cpp
- src/contact_constitutivelaw/4C_contact_constitutivelaw_linear_contactconstitutivelaw.hpp
- src/contact_constitutivelaw/4C_contact_constitutivelaw_mirco_contactconstitutivelaw.cpp
- src/contact_constitutivelaw/4C_contact_constitutivelaw_mirco_contactconstitutivelaw.hpp
- src/contact_constitutivelaw/4C_contact_constitutivelaw_power_contactconstitutivelaw.cpp
- src/contact_constitutivelaw/4C_contact_constitutivelaw_power_contactconstitutivelaw.hpp
Do some cleanup (comments, remove unused stuff, const qualifiers, ...) in rough surface contact framework.
> Some cleanup of rough surface code

- .github/dependabot.yml
Third time's the charm -- follows #327 and #1042
> Let dependabot look into subdirectories

- doc/documentation/src/analysis_guide_templates/geometrydefinition.rst.j2
- src/beaminteraction/src/4C_beaminteraction_submodel_evaluator_crosslinking.cpp
- src/browniandyn/4C_browniandyn_str_model_evaluator.cpp
- src/core/utils/src/random/4C_utils_random.cpp
- src/core/utils/src/random/4C_utils_random.hpp
- src/inpar/4C_inpar_particle.cpp
- src/particle_interaction/4C_particle_interaction_dem.cpp
- src/particle_interaction/4C_particle_interaction_dem_adhesion_surface_energy.cpp
- tests/input_files/beam3r_herm2line3_backweuler_browndyn_crosslinking_beam3rline2_belloffrate.4C.yaml
- tests/input_files/beam3r_herm2line3_backweuler_browndyn_randcrosslinking_beam3rline2.4C.yaml
- tests/input_files/beam3r_herm2line3_backweuler_browndyn_randcrosslinking_beam3rline2_twobonds.4C.yaml
- tests/input_files/beam3r_rigidsphere_activecrosslinking_truss_browndyn_truss_catchslipbond.4C.yaml
- tests/input_files/beam3r_rigidsphere_activecrosslinking_truss_browndyn_truss_forcedependetoffrate.4C.yaml
Found by #1033, Depends on #1030
Assert that stddev > 0 and change the naming and docs.
FYI @ppraegla @davidrudlstorfer
> Clarify normal distribution parameters

- src/solid_poro_3D_ele/4C_solid_poro_3D_ele_calc_lib.hpp
> Fix small bug in solid-poro Brinkmann flow off-diagonal block

- src/beaminteraction/src/4C_beaminteraction_beam_to_solid_mortar_manager.cpp
- src/beaminteraction/src/4C_beaminteraction_str_model_evaluator.cpp
- src/beaminteraction/src/4C_beaminteraction_str_model_evaluator_datastate.cpp
- src/constraint_framework/4C_constraint_framework_embeddedmesh_solid_to_solid_mortar_manager.cpp
- src/contact/4C_contact_lagrange_strategy.cpp
- src/contact/4C_contact_lagrange_strategy_wear.cpp
- src/contact/4C_contact_nitsche_strategy.cpp
- src/contact/4C_contact_nitsche_strategy_poro.cpp
- src/contact/4C_contact_nitsche_strategy_ssi.cpp
- src/contact/4C_contact_wear_interface.cpp
- src/core/linalg/src/sparse/4C_linalg_fevector.hpp
- src/coupling/src/adapter/4C_coupling_adapter.cpp
- src/ehl/4C_ehl_base.cpp
- src/fbi/4C_fbi_adapter_constraintbridge_penalty.cpp
- src/fbi/4C_fbi_beam_to_fluid_mortar_manager.cpp
- src/scatra/4C_scatra_timint_meshtying_strategy_s2i.cpp
This PR cleans up all the remaining `get_epetra_block_map` calls and some more `get_epetra_export` calls. 
#863
> Remove some raw Epetra calls

- utilities/create_json_schema.py
- utilities/metadata_utils.py
Follows #1014 #1030 
This PR allows validation of arbitrarily nested vector elements. @gilrrei Let me know if this fits in with your vision for the schemas. I have to say recursive code is quite nasty without static types :snake:
> Schema validation for vectors

- src/ale/4C_ale_meshtying.cpp
- src/fluid/4C_fluid_meshtying.cpp
> Remove a few non-configurable defines

- .typos.toml
- src/contact/src/4C_contact_abstract_strategy.hpp
- src/contact/src/4C_contact_lagrange_strategy_wear.cpp
- src/contact/src/4C_contact_meshtying_abstract_strategy.hpp
- src/contact/src/4C_contact_meshtying_poro_lagrange_strategy.hpp
- src/core/linalg/src/dense/4C_linalg_utils_densematrix_communication.hpp
- src/fbi/4C_fbi_constraintenforcer.hpp
- src/fpsi/4C_fpsi_monolithic.cpp
- src/fsi/src/monolithic/model_evaluator/4C_fsi_fluidfluidmonolithic_fluidsplit_nonox.cpp
- src/fsi/src/monolithic/model_evaluator/4C_fsi_fluidfluidmonolithic_structuresplit_nonox.hpp
- src/inpar/4C_inpar_mpc_rve.hpp
- src/mixture/4C_mixture_growth_strategy.hpp
- src/poroelast/4C_poroelast_monolithicsplit.hpp
- src/poroelast/4C_poroelast_monolithicsplit_nopenetration.hpp
- src/poroelast/4C_poroelast_monolithicstructuresplit.hpp
- src/w1/4C_w1_evaluate.cpp
Removed some typos in the spelling of Lagrange and to his name related tensors and multipliers.
> Remove n in La(n)grange

- utilities/validate_schema.py
Negative numbers were not captured
> Capture "-" sign in regex for schema validation

- src/core/linear_solver/src/method/4C_linear_solver_method_direct.cpp
Fixes https://github.com/4C-multiphysics/4C/pull/1155#issuecomment-3219196859
> Fix Epetra_Operator pointer in older versions

- src/core/linalg/src/sparse/4C_linalg_utils_sparse_algebra_math.cpp
This PR replaces some of the few `Epetra_CrsMatrix` calls with a `SparseMatrix`
#863
> Remove some EpetraCrs matrix calls

- apps/global_full/4C_global_full_io.cpp
- apps/global_full/4C_global_full_io.hpp
- apps/global_full/4C_global_full_main.cpp
- src/beaminteraction/src/4C_beaminteraction_beam_to_solid_visualization_output_writer_visualization.cpp
- src/core/comm/src/4C_comm_utils.cpp
- src/core/comm/src/4C_comm_utils.hpp
- src/core/comm/tests/4C_comm_utils_test.np3.cpp
- src/global_data/4C_global_data.cpp
- src/global_data/4C_global_data.hpp
- src/global_data/4C_global_data_read.cpp
- src/mat/4C_mat_aaaneohooke.cpp
- src/mat/4C_mat_constraintmixture.cpp
- src/mat/4C_mat_micromaterial_evaluate.cpp
- src/mat/4C_mat_scatra.cpp
- src/particle_algorithm/4C_particle_algorithm_sim.cpp
- src/stru_multi/4C_stru_multi_microstatic.cpp
- src/stru_multi/4C_stru_multi_microstatic_npsupport.cpp
- src/structure_new/src/4C_structure_new_timint_base.cpp
- src/structure_new/src/4C_structure_new_timint_basedatasdyn.cpp
- tests/benchmark_tests/solid_3D_ele/4C_solid_3D_ele_evaluation_benchmark.cpp
- unittests/mat/4C_electrode_test.cpp
... and some unused functions in Communicators.
> Remove shared_ptr on Communicators

- src/core/io/src/4C_io_input_spec_builders.hpp
- src/core/io/src/4C_io_input_types.hpp
- src/core/io/src/4C_io_value_parser.hpp
See https://github.com/4C-multiphysics/4C/pull/1178#discussion_r2306750764
#1178
> Rename rank to dynamic_rank

- src/core/linear_solver/src/method/4C_linear_solver_method_direct.cpp
Probably replaces #1215 and fixes #1213 and #760
I hope it passes, I could not check since my Trilinos is too old.
@maxfirmbach
> Fix UB in direct linear solver

- src/core/linalg/src/sparse/4C_linalg_sparsematrix.cpp
- src/core/linalg/src/sparse/4C_linalg_sparsematrix.hpp
- src/core/linalg/src/sparse/4C_linalg_sparseoperator.hpp
- src/core/linalg/src/sparse/4C_linalg_utils_sparse_algebra_create.cpp
- src/core/linalg/src/sparse/4C_linalg_utils_sparse_algebra_manipulation.cpp
- src/core/linalg/src/sparse/4C_linalg_utils_sparse_algebra_math.cpp
- src/core/linear_solver/src/amgnxn/4C_linear_solver_amgnxn_hierarchies.cpp
- src/core/linear_solver/src/amgnxn/4C_linear_solver_amgnxn_smoothers.cpp
- src/core/linear_solver/src/amgnxn/4C_linear_solver_amgnxn_smoothers.hpp
- src/core/linear_solver/src/method/4C_linear_solver_method_direct.cpp
- src/core/linear_solver/src/method/4C_linear_solver_method_iterative.cpp
- src/core/linear_solver/src/preconditioner/4C_linear_solver_preconditioner_ifpack.cpp
- src/core/linear_solver/src/preconditioner/4C_linear_solver_preconditioner_muelu.cpp
- src/core/linear_solver/src/preconditioner/4C_linear_solver_preconditioner_teko.cpp
- src/core/rebalance/src/4C_rebalance_graph_based.cpp
The sparse matrix reveiled the underlying non-const Epetra Matrix via `epetra_matrix()`.
I had to add two const_cast in the interface to Trilinos.
> Fix constness of SparseMatrix

- src/core/utils/src/stl_extension/4C_utils_flat_vector_vector.hpp
- src/core/utils/tests/stl_extension/4C_utils_flat_vector_vector_test.cpp
A performant vector<vector<T>> storing data and offsets
> Add FlatVectorVector<T> data structure

- src/core/fem/src/discretization/4C_fem_discretization_iterator.hpp
- src/core/fem/tests/discretization/4C_fem_discretization_iterator_test.cpp
Since we iterate over an index array with this Iterator, we can
- make it a random access iterator
- enable views on the iterator range
- provide a make_iterator_range helper
#1228
> Enhance DiscretizationIterator functionality 

- src/contact/src/4C_contact_interface.cpp
- src/core/binstrategy/4C_binstrategy.cpp
- src/core/binstrategy/4C_binstrategy.hpp
- src/core/fem/src/discretization/4C_fem_discretization.hpp
- src/core/fem/src/discretization/4C_fem_discretization_evaluate.cpp
- src/core/fem/src/discretization/4C_fem_discretization_fillcomplete.cpp
- src/core/fem/src/general/utils/4C_fem_general_l2_projection.cpp
- src/core/io/src/4C_io.cpp
- src/core/io/src/4C_io_discretization_visualization_writer_mesh.cpp
- src/core/rebalance/src/4C_rebalance_graph_based.cpp
- src/mat/4C_mat_micromaterialgp_static.cpp
- src/mortar/src/4C_mortar_interface.cpp
- src/poroelast/4C_poroelast_utils.cpp
- src/poroelast_scatra/4C_poroelast_scatra_utils.cpp
- src/reduced_lung/src/4C_reduced_lung_main.cpp
- src/shell7p/4C_shell7p_utils.cpp
- src/stru_multi/4C_stru_multi_microstatic.cpp
- src/structure_new/src/model_evaluator/4C_structure_new_model_evaluator_multiscale.cpp
- src/structure_new/src/model_evaluator/4C_structure_new_model_evaluator_structure.cpp
Roll out the new iterators to `my_(row|col)_element_range()`.
Part of #1228
> Use ElementRef in discretization loops

- src/structure_new/src/4C_structure_new_integrator.cpp
Fixing what I did slightly wrong in #1238
> Fix Epetra error in solid compute initial state

- src/beaminteraction/src/4C_beaminteraction_str_model_evaluator.cpp
- src/core/binstrategy/4C_binstrategy.cpp
- src/core/binstrategy/4C_binstrategy_utils.cpp
- src/core/fem/src/condition/4C_fem_condition_point_coupling_redistribution.cpp
- src/core/io/src/4C_io_meshreader.cpp
- src/core/io/src/4C_io_meshreader.hpp
- src/core/rebalance/src/4C_rebalance.cpp
- src/core/rebalance/src/4C_rebalance.hpp
- src/core/rebalance/src/4C_rebalance_binning_based.cpp
- src/core/rebalance/src/4C_rebalance_print.cpp
- src/core/rebalance/src/4C_rebalance_print.hpp
- src/global_data/4C_global_data_read.cpp
- src/porofluid_pressure_based/4C_porofluid_pressure_based_utils.cpp
- src/red_airways/4C_red_airways_implicitintegration.cpp
- src/scatra/4C_scatra_timint_heterogeneous_reaction_strategy.cpp
- src/ssi/4C_ssi_dyn.cpp
- src/xfem/4C_xfem_discretization_utils.cpp
Rebalancing is independent of mesh input and useful in its own right.
> Extract rebalancing from mesh input

- tests/input_files/cardiovascular0d_syspulcirculation_2chamber_structure_simple_genalpha.4C.yaml
- tests/input_files/xml/block_preconditioner/cardiovascular_solid.xml
The cardiovascular block is very small so that we can use a direct solver.
> Use BGS with Amesos KLU for cardiovascular block

- src/core/linalg/src/dense/4C_linalg_serialdensevector.hpp
Does this already solve the problem of #1304 ?
Closes #1304
> Fix: include of span in serial dense vector

- src/core/rebalance/src/4C_rebalance.cpp
- src/core/rebalance/src/4C_rebalance.hpp
- src/core/rebalance/src/4C_rebalance_input.cpp
- src/global_data/4C_global_data.hpp
- src/global_data/4C_global_data_read.cpp
> Use a struct for rebalance parameters

- doc/documentation/src/analysis_guide_templates/preprocessing.rst
This adds a small section to the preprocessing section.
We would also need a tutorial showing how to do it step by step. I will do it in another PR.
> Add some vtu preprocessing information to documentation
